### ISSUE TITLE
!game cannot be without param

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1004]
### Actual behavior
!game [user]
2018-05-29T19:38:14.602 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> Error: Object to update cannot be empty
at IMongoDB.update (/libs/databases/mongodb.js:190:34)
at Object.setGame [as fnc] (/libs/twitch.js:372:58)
at Parser.command /libs/parser.js:177:54)
at process._tickCallback (internal/process/next_tick.js:178:7) } reason: Error: Object to update cannot be empty

**Comment by sogehige** [comment]
What version? Any additional information? There is already check for that https://github.com/sogehige/sogeBot/blob/master/libs/twitch.js#L376

**Comment by sogehelper** [comment]
Latest master. I have this fix.
![img](https://i.imgur.com/ZISJOjQ.png)
