### ISSUE TITLE
Crash when clicking HIGHLIGHT in UPTIME stats

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#1022]
### Steps to reproduce
Click on HIGHLIGHT in the UPTIME stats bar. Easily replicated on every run of the bot.
### Additional information
2018-06-09T16:19:50.805 !!! ERROR !!! uncaughtException: Cannot read property '_id' of undefined
TypeError: Cannot read property '_id' of undefined
    at C:\sogeBot\libs\systems\highlights.js:101:87
    at Request._callback (C:\sogeBot\node_modules\twitch-js\lib\api.js:18:7)
    at Request.self.callback (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:1044:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:965:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2018-06-09T16:19:50.806 !!! ERROR !!! TypeError: Cannot read property '_id' of undefined
    at C:\sogeBot\libs\systems\highlights.js:101:87
    at Request._callback (C:\sogeBot\node_modules\twitch-js\lib\api.js:18:7)
    at Request.self.callback (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:1044:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\sogeBot\node_modules\twitch-js\node_modules\request\request.js:965:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2018-06-09T16:19:50.806 !!! ERROR !!! +------------------------------------------------------------------------------+
2018-06-09T16:19:50.806 !!! ERROR !!! | BOT HAS UNEXPECTEDLY CRASHED                                                 |
2018-06-09T16:19:50.806 !!! ERROR !!! | PLEASE CHECK https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue |
2018-06-09T16:19:50.806 !!! ERROR !!! | AND ADD logs/exceptions.log file to your report                              |
2018-06-09T16:19:50.806 !!! ERROR !!! +------------------------------------------------------------------------------+
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sogebot@7.5.1 start: `node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sogebot@7.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\\[USERNAME]\AppData\Roaming\npm-cache\_logs\2018-06-09T23_19_50_964Z-debug.log

**Comment by chiefstank** [comment]
2018-06-10T11:15:39.383 DEBUG: ======= COPY DEBUG MESSAGE FROM HERE ======= 
2018-06-10T11:15:39.383 DEBUG: GENERAL | OS: npm/5.6.0 node/v10.1.0 win32 x64 | DB: nedb | Bot version: 7.5.1 | Bot uptime: 21.242 | Bot lang: en | Bot mute: false 
2018-06-10T11:15:39.383 DEBUG: SYSTEMS | timers, customcommands, keywords, points, price, alias, moderation, ranks, bets, raffles, queue, cooldown, gambling, highlights 
2018-06-10T11:15:39.384 DEBUG: WIDGETS | raffles, chat, eventlist, twitter 
2018-06-10T11:15:39.384 DEBUG: OAUTH | BOT true | BROADCASTER true 
2018-06-10T11:15:39.385 DEBUG: ======= END OF DEBUG MESSAGE =======
