### ISSUE TITLE
JS variable not working

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1031]
### Actual behavior
I have variable with code
```javascript
var emotes = url('https://decapi.me/twitch/subscriber_emotes/soge__');
var list = _.join(emotes.emotes, ' ');
return list;
```
when i  click test script or when i use command in chat with that  variable, then nothing happens.
No errors in console
### Additional informations

Latest master, mongodb

**Comment by sogehige** [comment]
url didn't return correct axios object

```
var emotes = url('https://decapi.me/twitch/subscriber_emotes/soge__');
var list = _.join(emotes.data.emotes, ' ');
return list;
```

**Comment by sogehelper** [comment]
now i have error in bot console
```
2018-06-12T05:54:34.387 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> RangeError: Maximum call stack size exceeded
 at isBuf (node_modules/socket.io-parser/is-buffer.js:21:15)
at _removeBlobs (node_modules/socket.io-parser/binary.js:128:44)
at _removeBlobs (node_modules/socket.io-parser/binary.js:130:9) } reason: RangeErrr: Maximum call stack size exceeded
```

**Comment by sogehelper** [comment]
oh, nevermind, your code is working.
