### ISSUE TITLE
Unknown error on console

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#1046]
The bot did not crash only showed error. 

2018-06-14T04:53:59.036 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> { Error: Can't insert key renttukessu, it violates the unique constraint
    at _AVLTree.insert (C:\sogeBot\node_modules\binary-search-tree\lib\avltree.js:273:19)
    at AVLTree.insert (C:\sogeBot\node_modules\binary-search-tree\lib\avltree.js:307:27)
    at Index.insert (C:\sogeBot\node_modules\nedb\lib\indexes.js:77:15)
    at Datastore.addToIndexes (C:\sogeBot\node_modules\nedb\lib\datastore.js:180:29)
    at Datastore._insertMultipleDocsInCache (C:\sogeBot\node_modules\nedb\lib\datastore.js:416:12)
    at Datastore._insertInCache (C:\sogeBot\node_modules\nedb\lib\datastore.js:400:10)
    at Datastore._insert (C:\sogeBot\node_modules\nedb\lib\datastore.js:348:10)
    at C:\sogeBot\node_modules\nedb\lib\executor.js:40:13
    at Immediate.process (C:\sogeBot\node_modules\async\lib\async.js:731:21)
    at runCallback (timers.js:696:18) key: 'renttukessu', errorType: 'uniqueViolated' } } reason: Error: Can't insert key renttukessu, it violates the unique co
nstraint

2018-06-14T15:56:28.486 DEBUG: ======= COPY DEBUG MESSAGE FROM HERE =======
2018-06-14T15:56:28.488 DEBUG: GENERAL | OS: npm/5.6.0 node/v10.1.0 win32 x64 | DB: nedb | Bot version: 7.5.1 | Bot uptime: 361630.929 | Bot lang: en | Bot mute
: false
2018-06-14T15:56:28.491 DEBUG: SYSTEMS | timers, customcommands, keywords, points, price, alias, moderation, ranks, bets, raffles, queue, cooldown, gambling, hi
ghlights
2018-06-14T15:56:28.491 DEBUG: WIDGETS | twitter, eventlist, chat, raffles
2018-06-14T15:56:28.492 DEBUG: OAUTH | BOT true | BROADCASTER true
2018-06-14T15:56:28.492 DEBUG: ======= END OF DEBUG MESSAGE =======

**Comment by sogehige** [comment]
Ok, I believe I found a culprit for this issue. Is your channel bigger? I removed unique constraint, as it is not really needed for that.

**Comment by chiefstank** [comment]
No it's not big, but it's up 24/7 and people are in and out constantly. 20-70 viewers at all times. Lots of chatters in and out too.

**Comment by sogehige** [comment]
Yes, than it is possible, I've got two checks on same thing (checking if user is online chatter or not) and possibly those two functions got race condition and doing same thing at same time

**Comment by chiefstank** [comment]
FWIW, here is another occurrence today, just in case. :)

2018-07-31T20:01:20.882 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> { Error: Can't insert key lemiewinx, it violates the unique constraint
    at _AVLTree.insert (C:\sogeBot\node_modules\binary-search-tree\lib\avltree.js:273:19)
    at AVLTree.insert (C:\sogeBot\node_modules\binary-search-tree\lib\avltree.js:307:27)
    at Index.insert (C:\sogeBot\node_modules\nedb\lib\indexes.js:77:15)
    at Datastore.addToIndexes (C:\sogeBot\node_modules\nedb\lib\datastore.js:180:29)
    at Datastore._insertMultipleDocsInCache (C:\sogeBot\node_modules\nedb\lib\datastore.js:416:12)
    at Datastore._insertInCache (C:\sogeBot\node_modules\nedb\lib\datastore.js:400:10)
    at Datastore._insert (C:\sogeBot\node_modules\nedb\lib\datastore.js:348:10)
    at C:\sogeBot\node_modules\nedb\lib\executor.js:40:13
    at Immediate.process (C:\sogeBot\node_modules\async\lib\async.js:731:21)
    at runCallback (timers.js:696:18) key: 'lemiewinx', errorType: 'uniqueViolated' } } reason: Error: Can't insert key lemiewinx, it violates the unique constraint

2018-07-31T22:40:07.591 DEBUG: ======= COPY DEBUG MESSAGE FROM HERE =======
2018-07-31T22:40:07.592 DEBUG: GENERAL | OS: npm/5.6.0 node/v10.1.0 win32 x64 | DB: nedb | Bot version: 7.5.1 | Bot uptime: 41460.82 | Bot lang: en | Bot mute:
false
2018-07-31T22:40:07.592 DEBUG: SYSTEMS | timers, customcommands, keywords, points, price, alias, moderation, ranks, bets, raffles, queue, cooldown, gambling, hi
ghlights
2018-07-31T22:40:07.593 DEBUG: WIDGETS | eventlist, raffles, chat, twitter
2018-07-31T22:40:07.593 DEBUG: OAUTH | BOT true | BROADCASTER true
2018-07-31T22:40:07.593 DEBUG: ======= END OF DEBUG MESSAGE =======
