### ISSUE TITLE
Unknown error on Console

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#1094]
```
2018-07-10T19:26:30.737 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot create property 'Symbol(level)' on string 'stop'
    at DerivedLogger.log (/home/ayysir/soge/node_modules/winston/lib/winston/logger.js:130:20)
    at DerivedLogger.(anonymous function).args [as stop] (/home/ayysir/soge/node_modules/winston/lib/winston/create-logger.js:62:21)
    at API.getCurrentStreamData (/home/ayysir/soge/libs/api.js:670:22) } reason: TypeError: Cannot create property 'Symbol(level)' on string 'stop'
```

**Comment by sogehige** [comment]
Please provide additional informations, what commit you are on master, etc.
