### ISSUE TITLE
Raid exception

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#1169]
2018-08-11T01:55:32.132 +raid undefined, viewers: undefined
2018-08-11T01:55:32.146 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> Error: Object to update cannot be empty
    at INeDB.update (/root/bots/sogebot/src/bot/databases/nedb.js:203:34)
    at process.on (/root/bots/sogebot/cluster.js:80:51)
    at process.emit (events.js:185:15)
    at emit (internal/child_process.js:783:12)
    at process._tickCallback (internal/process/next_tick.js:178:19) } reason: Error: Object to update cannot be empty

**Comment by sogehige** [comment]
Should be fixed
