### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by imetallix** [sogehige/sogeBot#1226]
Hi! 
I'm no JS expert, this is my first time trying to run node.js program, after installing (with both npm and yarn) the modules, I get the following error when trying to start:

Error: Cannot find module '../dest/logging'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._resolveFilename (D:\GitProjects\Bot\node_modules\module-alias\index.js:49:29)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\GitProjects\Bot\tools\migrate.js:11:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
Done in 0.29s.

Any ideas what might have caused the problem?
Thanks a lot

**Comment by sogehige** [comment]
I guess you are running `master`, did you go through steps at http://sogehige.github.io/sogeBot/#/install-and-upgrade?id=installation-snapshot ?

**Comment by imetallix** [comment]
As I said, I'm a JS noob :P 
Thanks, works perfectly, well done mate.

**Comment by sogehige** [comment]
Great! If you have any issues, you can get help at discord https://discordapp.com/invite/52KpmuH
