### ISSUE TITLE
TMI Error on startup

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#1239]
2018-08-28T19:31:32.707 !!! ERROR !!! { TypeError: Cannot read property 'userState' of undefined
    at Chat.userState (/root/bots/sogebot/node_modules/twitch-js/src/Chat/index.js:494:29)
    at Client.emit (/root/bots/sogebot/node_modules/eventemitter3/index.js:181:35)
    at emit (/root/bots/sogebot/node_modules/twitch-js/src/Chat/Client.js:116:12)
    at Array.forEach (<anonymous>)
    at Client.forEach (/root/bots/sogebot/node_modules/twitch-js/src/Chat/Client.js:84:14)
    at WebSocket.onMessage (/root/bots/sogebot/node_modules/twitch-js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/root/bots/sogebot/node_modules/twitch-js/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/root/bots/sogebot/node_modules/twitch-js/node_modules/ws/lib/receiver.js:414:14)
  timestamp: 2018-08-28T19:31:32.658Z,
  _raw:
   ':soge__.tmi.twitch.tv 353 soge__ = #soge__ :vojtaszesrotiste decafsmurf inagawa soge__ name977 commanderroot 0_applebadapple_0 soge__bot skinnyseahorse\r\n:soge__.tmi.twitch.tv 366 soge__ #soge__ :End of /NAMES list\r\n:jtv MODE #soge__ +o soge__bot\r\n:jtv MODE #soge__ +o soge__\r\n',

**Comment by sogehige** [comment]
Cannot reproduce always...restart of bot usually is ok
