### ISSUE TITLE
Error on start, new bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1240]
### Actual behavior
```
0|bot  | 2018-08-28T16:39:17.518 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
0|bot  |   <rejected> TypeError: Cannot read property 'data' of undefined
0|bot  |     at API.data [as oauthValidation] (/root/bots/testbot/src/bot/api.js:81:85)
0|bot  |     at new oauthValidation (/root/bots/testbot/src/bot/api.js:47:12)
0|bot  |     at main (/root/bots/testbot/src/bot/main.js:67:16)
0|bot  |     at Timeout.main [as _onTimeout] (/root/bots/testbot/src/bot/main.js:54:60)
0|bot  |     at ontimeout (timers.js:424:11)
0|bot  |     at tryOnTimeout (timers.js:288:5)
0|bot  |     at listOnTimeout (timers.js:251:5)
0|bot  |     at Timer.processTimers (timers.js:211:10) } reason: TypeError: Cannot read property 'data' of undefined
0|bot  | 2018-08-28T16:39:17.561 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
0|bot  |   <rejected> { Invariant Violation: [twitch-js/Chat] options: Expected valid options
0|bot  |     at invariant (/root/bots/testbot/node_modules/invariant/invariant.js:40:15)
0|bot  |     at Object.chatOptions (/root/bots/testbot/node_modules/twitch-js/src/Chat/utils/validators.js:46:3)
0|bot  |     at Chat.chatOptions (/root/bots/testbot/node_modules/twitch-js/src/Chat/index.js:114:32)
0|bot  |     at new Chat (/root/bots/testbot/node_modules/twitch-js/src/Chat/index.js:85:5)
0|bot  |     at new TwitchJs (/root/bots/testbot/node_modules/twitch-js/src/index.js:39:17)
0|bot  |     at main (/root/bots/testbot/src/bot/main.js:85:27)
0|bot  |     at Timeout.main [as _onTimeout] (/root/bots/testbot/src/bot/main.js:54:60)
0|bot  |     at ontimeout (timers.js:424:11)
0|bot  |     at tryOnTimeout (timers.js:288:5)
0|bot  |     at listOnTimeout (timers.js:251:5) name: 'Invariant Violation', framesToPop: 1 } } reason: Invariant Violation: [twitch-js/Chat] options: Expected valid options
```
i have that erorr on bot starting.
Mine bot is clear, so it's new bot.

**Comment by sogehige** [comment]
Your oauths are wrong

**Comment by sogehige** [comment]
also again, missing informations about version.....

**Comment by Banonevar** [comment]
There was some oauth problem. I just did renew.
