### ISSUE TITLE
[8.0.1] Error: Cannot find module '../dest/logging'

### ISSUE THREAD

**Issue by hieblmedia** [sogehige/sogeBot#1289]
Get following error message after upgrading. Testesd also with a fresh installation.
NodeJS 8.11.4

```
# npm start
Error: Cannot find module '../dest/logging'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._resolveFilename (/opt/sogeBot-current/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/sogeBot-current/tools/migrate.js:11:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by sogehige** [comment]
Are you using git version or released version?

**Comment by hieblmedia** [comment]
Oh my bad. Downloaded the SourceCode zip by mistake.

**Comment by sogehige** [comment]
No problem, cheers!
