### ISSUE TITLE
Unexpected error when launching bot

### ISSUE THREAD

**Issue by MoonlightAshe** [sogehige/sogeBot#1290]
### Expected behavior
Start up bot
### Actual behavior
Bot crashes, or actually runs at first but stops without giving notice
### Steps to reproduce
Currently using Ubuntu 18.04 but unsure if that is the issue, otherwise it happens when starting up the bot sometimes.
### Additional information

exceptions.log

2018-09-06T03:48:54.926 !!! ERROR !!! uncaughtException: spawn ENOMEM
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:525:9)
    at fork (child_process.js:108:10)
    at createWorkerProcess (internal/cluster/master.js:134:10)
    at EventEmitter.cluster.fork (internal/cluster/master.js:170:25)
    at fork (/home/bot/sogebot/src/bot/main.js:159:24)
    at EventEmitter.fork (/home/bot/sogebot/src/bot/main.js:46:40)
    at EventEmitter.emit (events.js:182:13)
    at ChildProcess.worker.process.once (internal/cluster/master.js:216:13)
    at Object.onceWrapper (events.js:273:13)

**Comment by sogehige** [comment]
Thats first time I am seeing this error. This error is basically **out of memory** error

Do you have minimal prerequisites for a bot? http://sogehige.github.io/sogeBot/#/install-and-upgrade?id=prerequisites

**Comment by sogehige** [comment]
No new comments, closing
