### ISSUE TITLE
!watched shows always 0.0

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1335]
### Actual behavior
!watched shows always 0.0, on primary key id
### Additional informations

Mongodb, master (https://github.com/sogehige/sogeBot/commit/8d5c122a294c494ec6001a072975be66078edfb2)

**Comment by Banonevar** [comment]
```
Deprecated: users.get, use getById or getByName
Error
at Users.get (/root/bots/src/bot/users.js:76:18)
at Twitch.get [as watched] (/root/bots/src/bot/twitch.js:237:39)
at Parser.apply [as command] (/root/bots/src/bot/parser.js:201:85)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
