### ISSUE TITLE
Top time not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1372]
### Actual behavior
```
2018-09-25T21:43:59.488 <<< !top time [me]
2018-09-25T21:43:59.801 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'username' of undefined
at Commons.username [as isIgnored] (/root/bots/src/bot/commons.js:56:60)
at Twitch.isIgnored [as showTop] (/root/bots/src/bot/twitch.js:330:28)
at process._tickCallback (internal/process/next_tick.js:68:7) } reason: TypeError: Cannot read property 'username' of undefined
```

**Comment by Banonevar** [comment]
And same for !top messages, but !top points working

**Comment by sogehige** [comment]
Cannot reproduce, please append your users, users.messaged and users.watched collections

**Comment by sogehige** [comment]
Please append your collections to get this fixed

**Comment by Banonevar** [comment]
[Desktop.zip](https://github.com/sogehige/sogeBot/files/2444653/Desktop.zip)
