### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1388]
### Actual behavior
```
1|bot  | 2018-09-28T22:41:39.528 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
1|bot  |   <rejected> { Error: Request failed with status code 401
1|bot  |     at createError (/root/bots/bot/node_modules/axios/lib/core/createError.js:16:15)
1|bot  |     at settle (/root/bots/bot/node_modules/axios/lib/core/settle.js:18:12)
1|bot  |     at IncomingMessage.handleStreamEnd (/root/bots/bot/node_modules/axios/lib/adapters/http.js:201:11)
1|bot  |     at IncomingMessage.emit (events.js:187:15)
1|bot  |     at endReadableNT (_stream_readable.js:1085:12)
1|bot  |     at process._tickCallback (internal/process/next_tick.js:63:19)
1|bot  |   config:
1|bot  |    { adapter: [Function: httpAdapter],
1|bot  |      transformRequest: [Object],
1|bot  |      transformResponse: [Object],
1|bot  |      timeout: 0,
1|bot  |      xsrfCookieName: 'XSRF-TOKEN',
1|bot  |      xsrfHeaderName: 'X-XSRF-TOKEN',
1|bot  |      maxContentLength: -1,
1|bot  |      validateStatus: [Function: validateStatus],
1|bot  |      headers: [Object],
1|bot  |      method: 'get',
1|bot  |      url: 'https://api.twitch.tv/helix/users?id=87608529',
1|bot  |      data: undefined },
1|bot  |   request:
1|bot  |    ClientRequest {
1|bot  |      _events: [Object],
1|bot  |      _eventsCount: 6,
1|bot  |      _maxListeners: undefined,
1|bot  |      output: [],
1|bot  |      outputEncodings: [],
1|bot  |      outputCallbacks: [],
1|bot  |      outputSize: 0,
1|bot  |      writable: true,
1|bot  |      _last: true,
1|bot  |      chunkedEncoding: false,
1|bot  |      shouldKeepAlive: false,
1|bot  |      useChunkedEncodingByDefault: false,
1|bot  |      sendDate: false,
1|bot  |      _removedConnection: false,
1|bot  |      _removedContLen: false,
1|bot  |      _removedTE: false,
1|bot  |      _contentLength: 0,
1|bot  |      _hasBody: true,
1|bot  |      _trailer: '',
1|bot  |      finished: true,
1|bot  |      _headerSent: true,
1|bot  |      socket: [TLSSocket],
1|bot  |      connection: [TLSSocket],
1|bot  |      _header:
1|bot  |       'GET /helix/users?id=87608529 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: OAuth i0b1hdinp78ohxdwajiltj18q2y0yl\r\nUser-Agent: axios/0.18.0\r\nHost: api.twitch.tv\r\nConnection: close\r\n\r\n',
1|bot  |      _onPendingData: [Function: noopPendingOutput],
1|bot  |      agent: [Agent],
1|bot  |      socketPath: undefined,
1|bot  |      timeout: undefined,
1|bot  |      method: 'GET',
1|bot  |      path: '/helix/users?id=87608529',
1|bot  |      _ended: true,
1|bot  |      res: [IncomingMessage],
1|bot  |      aborted: undefined,
1|bot  |      timeoutCb: null,
1|bot  |      upgradeOrConnect: false,
1|bot  |      parser: null,
1|bot  |      maxHeadersCount: null,
1|bot  |      _redirectable: [Writable],
1|bot  |      [Symbol(isCorked)]: false,
1|bot  |      [Symbol(outHeadersKey)]: [Object] },
1|bot  |   response:
1|bot  |    { status: 401,
1|bot  |      statusText: 'Unauthorized',
1|bot  |      headers: [Object],
1|bot  |      config: [Object],
1|bot  |      request: [ClientRequest],
1|bot  |      data: [Object] } } } reason: Error: Request failed with status code 401
```

**Comment by Banonevar** [comment]
Master at https://github.com/sogehige/sogeBot/commit/11d8331567a5a8479589c9b49bb83982cf318c96 commit
