### ISSUE TITLE
!top time isIgnored error

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#1421]
```
2018-10-01T23:47:54.595 <<< !top time [***]
2018-10-01T23:47:54.846 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'username' of undefined
    at Commons.username [as isIgnored] (D:\_GIT\sogeBot\src\bot\commons.js:64:60)
    at Twitch.isIgnored [as showTop] (D:\_GIT\sogeBot\src\bot\twitch.js:333:34) } reason: TypeError: Cannot read property 'username' of undefined
```

**Comment by sogehige** [comment]
Probably test db was broken
