### ISSUE TITLE
Error parsing subscription event

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1442]
### Actual behavior
```
018-10-08T10:25:41.341 !!! ERROR !!! Error parsing subscription event
2018-10-08T10:25:41.375 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
rejected> TypeError: global.log.errro is not a function
at TMI.errro [as subscription] (/root/bots/src/bot/tmi.js:278:18)
at process._tickCallback (internal/process/next_tick.js:68:7) } reason: TypeError: global.log.errro is not a function
```
Got this error on subscribtion event
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/c4db5c5b6dd798b5f4d5104166324348dd765ac2

**Comment by sogehige** [comment]
Fixed error typo, although this might not be fixed yet

**Comment by Banonevar** [comment]
```
2018-10-13T12:29:37.229 !!! ERROR !!! Error parsing subscription event 
2018-10-13T12:29:37.230 !!! ERROR !!! {"_raw":"@badges=subscriber/0;color=#5F9EA0;display-name=Y0UR_FEAR;emotes=;flags=;id=2d177c6c-cbbe-4e5b-8c39-7cf05faa2f95;login=y0ur_fear;mod=0;msg-id=sub;msg-param-months=1;msg-param-sub-plan-name=Channel\\sSubscription\\s(hidden);msg-param-sub-plan=1000;room-id=106729827;subscriber=1;system-msg=Y0UR_FEAR\\sjust\\ssubscribed\\swith\\sa\\sTier\\s1\\ssub!;tmi-sent-ts=1539422977180;turbo=0;user-id=82037383;user-type= :tmi.twitch.tv USERNOTICE #hidden","timestamp":"2018-10-13T09:29:37.180Z","command":"USERNOTICE","channel":"#hidden","tags":{"badges":{"subscriber":0},"color":"#5F9EA0","displayName":"Y0UR_FEAR","emotes":[],"flags":true,"id":"2d177c6c-cbbe-4e5b-8c39-7cf05faa2f95","login":"y0ur_fear","mod":"0","msgId":"sub","msgParamMonths":"1","msgParamSubPlanName":"Channel\\sSubscription\\s(hidden)","msgParamSubPlan":"1000","roomId":"106729827","subscriber":"1","systemMsg":"Y0UR_FEAR just subscribed with a Tier 1 sub!","tmiSentTs":"1539422977180","turbo":"0","userId":"82037383","isModerator":false,"isSubscriber":true,"isSubGifter":false,"isTurboSubscriber":false},"isSelf":false,"parameters":{"months":1,"subPlanName":"Channel Subscription (hidden)","subPlan":"1000"},"event":"SUBSCRIPTION","systemMessage":"Y0UR_FEAR just subscribed with a Tier 1 sub!"} 
2018-10-13T12:29:37.232 !!! ERROR !!! TypeError: Cannot read property 'username' of undefined
    at Commons.username [as isIgnored] (/root/bots/src/bot/commons.js:60:60)
    at TMI.isIgnored [as subscription] (/root/bots/src/bot/tmi.js:263:32)
    at Chat.subscription (/root/bots/src/bot/tmi.js:194:16)
    at Chat.emit (/root/bots//node_modules/eventemitter3/index.js:181:35)
    at /root/bots//node_modules/twitch-js/src/Chat/index.js:405:11
    at Array.reduce (<anonymous>)
    at Chat.reduce [as emit] (/root/bots//node_modules/twitch-js/src/Chat/index.js:403:10)
    at Chat.emit (/root/bots//node_modules/twitch-js/src/Chat/index.js:576:8)
    at Client.emit (/root/bots//node_modules/eventemitter3/index.js:181:35)
    at emit (/root/bots//node_modules/twitch-js/src/Chat/Client.js:120:12) 
```
