### ISSUE TITLE
Could not get bot to chat

### ISSUE THREAD

**Issue by AlexandreBlause** [sogehige/sogeBot#1484]
```

2018-10-26T00:52:44.257 !!! ERROR !!! uncaughtException: Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at Socket.join (/var/www/fritos.be/panel/src/bot/panel.js:176:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at /var/www/fritos.be/panel/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2018-10-26T00:56:08.133 !!! ERROR !!! uncaughtException: Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at Socket.join (/var/www/fritos.be/panel/src/bot/panel.js:176:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at /var/www/fritos.be/panel/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by sogehige** [comment]
It seems you are missing broadcaster_username configuration in config.json
```
{
  settings: {
    broadcaster_username: 'your_channel'
  }
}
```
