### ISSUE TITLE
OwnSystem onChange not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1495]
### Actual behavior
I want do some function, on token change from webpanel, as i understand
```javascript
const settings = {
 token: ''
}
const onChange = {
  'token': ['update']
 }
```
Where is **token** it's key, where is **update** it's function what will be runned onChange
But i got error in console when i change token from SogeBot Web Dashboard
```
2018-11-03T08:50:13.945 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: global[a] is not a function
      at Object.set (E:\bot\src\bot\_interface.js:142:13)
      at Socket.a.on ((E:\bot\src\bot\_interface.js:231:22)
      at Socket.emit (events.js:182:13)
      at (E:\bot\node_modules\socket.io\lib\socket.js:528:12
      at process._tickCallback (internal/process/next_tick.js:61:11) } reason: TypeError: global[a] is not a function
2018-11-03T08:50:13.951 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: global[a] is not a function
      at Object.set ((E:\\bot\src\bot\_interface.js:142:13)
      at baseAssignValue ((E:\\bot\node_modules\lodash\lodash.js:2559:21)
      at assignValue (E:\\bot\node_modules\lodash\lodash.js:2475:9)
      at baseSet ((E:\\bot\node_modules\lodash\lodash.js:3995:9)
      at Function.set ((E:\\bot\node_modules\lodash\lodash.js:13675:40)
      at process.set ((E:\\bot\src\bot\_interface.js:67:13)
      at process.emit (events.js:187:15)
      at process.emit ((E:\\bot\node_modules\source-map-support\source-map-support.js:461:21)
      at emit (internal/child_process.js:812:12)
      at process._tickCallback (internal/process/next_tick.js:63:19) } reason: TypeError: global[a] is not a function
```
### Steps to reproduce
create SomeSystem.js, and change token from WebPanel
```javascript
const System = require('./_interface')
const cluster = require('cluster')

class SomeSystem extends System {
  constructor () {
    const settings = {
      token: ''
    }
    const onChange = {
      'token': ['update']
    }
    super({settings, onChange})
    if (cluster.isMaster) {
      this.init()
    }
  }
  async init() {
    let token = await global.db.engine.findOne(this.collection.settings, { key: 'token' })
    if (token.value !== '') {
      console.log('inited')
    }
  }
  update() {
    console.log('updated')
  }
}

module.exports = new SomeSystem()
```

### Additional informations

Master (https://github.com/sogehige/sogeBot/commit/a3f3311846097dbbd592b85df7a9dfbe4e2d1cf0), mongodb

**Comment by sogehige** [comment]
You don't need to `let token = await global.db.engine.findOne(this.collection.settings, { key: 'token' })`, token should be loaded on start

**Comment by Banonevar** [comment]
it's load empty token, like `token: ''`
thats why i use it.
But what about onChange?

**Comment by sogehige** [comment]
It's not loading empty token if token is saved in db....don't use it nonintended way

**Comment by Banonevar** [comment]
But for me it's load empty on start. Thats why i use  global.db.engine.findOne

**Comment by Banonevar** [comment]
It's not bad, i think? i'm inderested how to do onChange function
1) i change token -> and some function fire
