### ISSUE TITLE
After move integrations to interface got doubled donations

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1655]
### Actual behavior
After that (https://github.com/sogehige/sogeBot/commit/efaff3bd233cca019f5e45adde7bd70b4372b9fa) commit, when someone donate on donationalerts, i got doubled donate event. Doubled everywhere, eventlist, user tip stats, doubled event (bot send message twice)
### Steps to reproduce
I noticed this on donationalerts, maybe this not exist on streamlabs integration

**Comment by Banonevar** [comment]
if you need reproduce, They have english language now, you need use secret token and click test notify in dashboard

**Comment by Banonevar** [comment]
Streamlabs is fine, no twiced events.
Issue exist only on donationalerts integration.

**Comment by Banonevar** [comment]
2018-12-04T15:06:34.323 | DONATIONALERTS.RU: Socket disconnected from service
2018-12-04T15:06:35.118 | DONATIONALERTS.RU: Successfully connected socket to service
2018-12-04T15:06:36.787 | DONATIONALERTS.RU: Socket disconnected from service
2018-12-04T15:06:37.595 | DONATIONALERTS.RU: Successfully connected socket to service

**Comment by sogehige** [comment]
I was not able to reproduce, can you check if https://github.com/sogehige/sogeBot/pull/1659 fixed your issue?

**Comment by Banonevar** [comment]
2018-12-04T17:25:54.617 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'removeAllListeners' of null
at Donationalerts.removeAllListeners [as disconnect] (/root/bots/src/bot/integrations/donationalerts.js:43:19)
 at Donationalerts.disconnect [as connect] (/root/bots//src/bot/integrations/donationalerts.js:48:10)
at Timeout.connect [as _onTimeout] (/root/bots//src/bot/integrations/donationalerts.js:32:28)
at ontimeout (timers.js:424:11)
at tryOnTimeout (timers.js:288:5)
at listOnTimeout (timers.js:251:5)
at Timer.processTimers (timers.js:211:10) } reason: TypeError: Cannot read property 'removeAllListeners' of null

**Comment by Banonevar** [comment]
And it again doubled, after reconnct
i mean after bot start, it's ok, not doubled
but when reconnected after an hour, then again doubled

**Comment by sogehige** [comment]
updated, try branch again please

**Comment by sogehige** [comment]
reproduced, found an issue

**Comment by sogehige** [comment]
it should be fixed now on branch, please test

**Comment by Banonevar** [comment]
Now fixed, thx.
