### ISSUE TITLE
403 error on title/game change (wizard of legend)

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#1715]
```
0|sogebot  | 2019-01-09T19:16:01.950 !!! ERROR !!! API: https://api.twitch.tv/kraken/channels/96965261 - Error: Request failed with status code 403
0|sogebot  |     at createError (/root/bots/sogebot/node_modules/axios/lib/core/createError.js:16:15)
0|sogebot  |     at settle (/root/bots/sogebot/node_modules/axios/lib/core/settle.js:18:12)
0|sogebot  |     at Unzip.handleStreamEnd (/root/bots/sogebot/node_modules/axios/lib/adapters/http.js:201:11)
0|sogebot  |     at Unzip.emit (events.js:193:15)
0|sogebot  |     at endReadableNT (_stream_readable.js:1129:12)
0|sogebot  |     at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by sogehige** [comment]
Accompanying issue on vue

```
vue.js:616 [Vue warn]: Error in render: "SyntaxError: Unexpected token / in JSON at position 1"

(found in <Root>)
warn @ vue.js:616
vue.js:1828 SyntaxError: Unexpected token / in JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (eval at createFunction (vue.js:10781), <anonymous>:3:2226)
    at Proxy.renderList (vue.js:3821)
    at Proxy.eval (eval at createFunction (vue.js:10781), <anonymous>:3:1692)
    at Vue._render (vue.js:4636)
    at Vue.updateComponent (vue.js:2893)
    at Watcher.get (vue.js:3261)
    at Watcher.run (vue.js:3336)
    at flushSchedulerQueue (vue.js:3094)
    at Array.<anonymous> (vue.js:1925)
```

**Comment by sogehige** [comment]
And kraken stats cannot be opened

**Comment by sogehige** [comment]
Heh funny its blocked by `cz/en 🧙 Merlin mi muze tak maximalne podrzet ... hulku !discord !social` as innapropriate title => we should have better ui response for this
