### ISSUE TITLE
Follow webhook error

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1733]
### Actual behavior
i see much errors in logs
```
2019-01-14T20:02:37.896 !!! ERROR !!! TypeError: Username is undefined
at Webhooks.TypeError [as follower] (/root/bots/bot/src/bot/webhooks.js:203:56)
at follower (/root/bots/bot/src/bot/panel.js:31:21)
at Layer.handle [as handle_request] (/root/bots/bot/node_modules/express/lib/router/layer.js:95:5)
at next (/root/bots/bot/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/root/bots/bot/node_modules/express/lib/router/route.js:112:3)
 at Layer.handle [as handle_request] (/root/bots/bot/node_modules/express/lib/router/layer.js:95:5)
 at /root/bots/bot/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/root/bots/bot/node_modules/express/lib/router/index.js:335:12)
at next (/root/bots/bot/node_modules/express/lib/router/index.js:275:10)
at urlencodedParser (/root/bots/bot/node_modules/body-parser/lib/types/urlencoded.js:82:7)
2019-01-14T20:02:37.897 !!! ERROR !!! {"data":{"from_id":"142918725","to_id":"139336353"},"id":"5c417b49-77d1-52bf-b4ab-2fffb50b1f6c","timestamp":"2019-01-14T17:02:18.895Z","topic":"https://api.twitch.tv/helix/users/follows?to_id=139336353","type":"create"}
```
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/8384a4495a46fd2dd88192f9d44a7f8b0b4fd975

**Comment by sogehige** [comment]
Is this still issue?

**Comment by Banonevar** [comment]
Nope
