### ISSUE TITLE
Problems with RegExp for command responses

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1938]
### Actual behavior
i have an !command, what reponse is $param, and i use  `(*)>` param
and bot wont send this message
### Steps to reproduce
```
rejected> SyntaxError: Invalid regular expression: /!command (*)>/: Nothing to repeat
at new RegExp (<anonymous>)
at Cooldown.check (/root/bots/bot/src/bot/systems/cooldown.js:84:25)
at processTicksAndRejections (internal/process/next_tick.js:81:5) } reason: SyntaxError: Invalid regular expression: /!command (*)>/: Nothing to repeat
```

**Comment by Banonevar** [comment]
```
2019-02-23T00:48:40.429 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> SyntaxError: Invalid regular expression: /!command B)/: Unmatched ')'
at new RegExp (<anonymous>)
at Cooldown.check (/root/bots/bot/src/bot/systems/cooldown.js:84:25)
at processTicksAndRejections (internal/process/next_tick.js:81:5) } reason: SyntaxError: Invalid regular expression: /!command B)/: Unmatched ')'
```

**Comment by sogehige** [comment]
Not sure if I understand your problem, this is invalid regex, so its basically correct error

**Comment by sogehige** [comment]
Do you have cooldown on that command?

**Comment by sogehige** [comment]
reproduced
