### ISSUE TITLE
Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by marcobuettner** [sogehige/sogeBot#1990]
### Expected behavior
I expect when I run 'npm start' that the bot starts

### Actual behavior
The bot crashs on start because of missing/not found module 'worker_threads'

### Steps to reproduce
I install the bot from scratch (v8.4.1) on a RHEL 7 with Nodejs v10.13.0

### Additional informations
`Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (/home/crss/bots/twitchbot/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (/home/crss/bots/twitchbot/src/bot/logging.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)`

**Comment by Banonevar** [comment]
You need nodejs v11

**Comment by sogehige** [comment]
Yes, thats correct latest LTS or current version should be used

http://sogehige.github.io/sogeBot/#/install-and-upgrade?id=prerequisites
