### ISSUE TITLE
(random.online.viewer) gives an error

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2042]
### Actual behavior
I use (random.online.viewer) filter and command gives error like
```
<rejected> TypeError: Cannot read property 'username' of undefined
at Commons.username [as isIgnored] (/root/bots/bot/src/bot/commons.js:72:60)
at isIgnored (/root/bots/sadrusty/src/bot/message.js:87:44)
at Array.filter (<anonymous>)
at filter (/root/bots/bot/src/bot/message.js:84:41)
at runNextTicks (internal/process/next_tick.js:47:5)
 at processImmediate (timers.js:610:7) } reason: TypeError: Cannot read property 'username' of undefined
```
### Steps to reproduce
use this filter in command
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/9438607348a182a93cf71282e6ec3bbbd26318cf

**Comment by sogehige** [comment]
Its consequence of #2043

**Comment by Banonevar** [comment]
now im get
```
<rejected> TypeError: Cannot read property 'username' of undefined
at Commons.username [as isIgnored] (/root/bots/bot/src/bot/commons.js:65:60)
at isIgnored (/root/bots/bot/src/bot/message.js:87:44)
at Array.filter (<anonymous>)
at filter (/root/bots/bot/src/bot/message.js:84:41) } reason: TypeError: Cannot read property 'username' of undefined
```
