### ISSUE TITLE
Error on cleanup

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2055]
### Actual behavior
i try to run cleanup, bot got error
```Cleaning up duplicates users
(node:2812) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'flatten' of undefined
    at INeDB.flatten [as find] (/root/bots/bot/src/bot/databases/nedb.js:107:43)
    at cleanUsersDuplicates (/root/bots/bot/tools/cleanup.js:60:31)
    at main (/root/bots/bot/tools/cleanup.js:100:9)
    at term.yesOrNo (/root/bots/bot/tools/cleanup.js:35:7)
    at onKey (/root/bots/bot/node_modules/terminal-kit/lib/yesOrNo.js:70:22)
    at Terminal.listenerWrapper (/root/bots/bot/node_modules/nextgen-events/lib/NextGenEvents.js:428:36)
    at Function.emitToOneListener (/root/bots/bot/node_modules/nextgen-events/lib/NextGenEvents.js:641:36)
    at Function.emitEvent (/root/bots/bot/node_modules/nextgen-events/lib/NextGenEvents.js:566:17)
    at Terminal.emit (/root/bots/bot/node_modules/nextgen-events/lib/NextGenEvents.js:500:23)
    at Terminal.onStdin (/root/bots/bot/node_modules/terminal-kit/lib/Terminal.js:1148:9)
```
### Additional informations

nedb, master https://github.com/sogehige/sogeBot/commit/55e880404d90ed6ba2fc0409216d155a939c3f67

**Comment by sogehige** [comment]
Cleanup is useless and not supported don't use it

Dne so 23. 3. 2019 11:46 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
and how i can clear doubled users then?

**Comment by sogehige** [comment]
You cannot have doubled users

Dne so 23. 3. 2019 13:55 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
I can send db and you will check, i have doubled

**Comment by sogehige** [comment]
This is already fixed on master
