### ISSUE TITLE
TypeError: glob is not a function [soundboard]

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2077]
### Actual behavior
```
2019-03-30T16:54:08.686 !!! ERROR !!! TypeError: glob is not a function
    at Socket.glob (/root/bots/bot/src/bot/widgets/soundboard.ts:17:9)
    at Socket.emit (events.js:197:13)
    at /root/bots/bot/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/next_tick.js:74:9) 
```
it's when click some sound in widget

**Comment by sogehige** [comment]
Working ok on 38dd0deefba3f98c9b1edca26deb7517a17343ba
