### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2078]
### Actual behavior
```
2019-03-31T18:08:04.594 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot convert undefined or null to object
 at Function.values (<anonymous>)
at Workers.values [as process] (/root/bots/bot/src/bot/workers.ts:178:32)
at MessagePort.process (/root/bots/bot/src/bot/workers.ts:241:48)
at MessagePort.emit (events.js:197:13)
at MessagePort.onmessage (internal/worker/io.js:68:8) } reason: TypeError: Cannot convert undefined or null to object
```
### Steps to reproduce
I haven't any idea why it happend, really

**Comment by sogehige** [comment]
Cannot reproduce it, added better error logging https://github.com/sogehige/sogeBot/pull/2079

**Comment by sogehige** [comment]
Is this still relevant?

**Comment by Banonevar** [comment]
Think not
