### ISSUE TITLE
No data in panel

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2202]
### Actual behavior
I noticed one weird thing. Sometimes after X hours bot uptime, panel working wrong.
For example if i open panel, there is not widgets.
If i open commands, it's fine
if i open Settings->bot, there is nothing too
if i open Polls, there is nothing too

But when i restart bot, it's load data correctly.
### Steps to reproduce
All i see in chrome debug, it's `main.js:80 Uncaught (in promise) configuration variable was not loaded`

**Comment by sogehige** [comment]
Are emotes loading in progress?

Dne út 21. 5. 2019 5:53 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Not sure

**Comment by Banonevar** [comment]
2019-06-16T13:46:38.573 |! !!! oauth.settings.general.0 object is not retroactive, for advanced object types use database directly.
2019-06-16T13:46:38.574 !!! ERROR !!! Error:
at Object.get (/root/bots//src/bot/_interface.ts:200:35)
at OAuth.getAllSettings (/root/bots//src/bot/_interface.ts:652:46)
at Socket.getAllSettings (/root/bots//src/bot/panel.js:308:50)
at Socket.emit (events.js:196:13)
 at /root/bots//node_modules/socket.io/lib/socket.js:528:12
at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by sogehige** [comment]
-[ ] - check if null tokens in db can cause infinite loop

**Comment by Banonevar** [comment]
Seems like this issue is gone. You can close i think.
