### ISSUE TITLE
Strange badges error

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2310]
### Actual behavior
```
2019-06-21T10:36:15.136 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot create property 'badges' on string 'username'
at TMI.message (/root/bots//src/bot/tmi.js:621:7)
at Workers.apply [as process] (/root/bots//src/bot/workers.ts:317:31)
 at MessagePort.process (/root/bots//src/bot/workers.ts:372:48)
at MessagePort.emit (events.js:200:13)
at MessagePort.onmessage (internal/worker/io.js:70:8)
} reason: TypeError: Cannot create property 'badges' on string 'username'
```
I not typed something in chat, but bot shows me that error, it's weird
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/2d2339acfd8aaef94af2381e266ec0f7868442d5

**Comment by Banonevar** [comment]
Where username it's my nickname, i'm bot owner (not channel, just owner)

**Comment by Banonevar** [comment]
It's happens on commands to, for example for `!quote -tag general`

**Comment by sogehige** [comment]
I cannot seem to reproduce

```
2019-06-24T11:47:36.430 <<< !quote -tag asd [soge__]
2019-06-24T11:47:36.905 >>> @soge__, žádné citace s tagem asd nebyly nalezeny. [soge__]
2019-06-24T11:47:44.615 <<< !quote -tag general [soge__]
2019-06-24T11:47:44.840 >>> Citace 2 od soge__ 'Lorem Ipsum' [soge__]
```

**Comment by Banonevar** [comment]
Well, it's not exactly on this command, it's happening randomly

**Comment by Banonevar** [comment]
oh no sorry, try to reproduce it by:
create command with response `(!quote -tag general)`

**Comment by Banonevar** [comment]
Same for timers

**Comment by Banonevar** [comment]
Again reproduced this, my way:
Created variable with response: (!mycommand)
`!mycommand` response: $_myvariable
And got same issue with badges
