### ISSUE TITLE
cvar error

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#2394]
```
2019-07-05T18:32:55.531 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'username' of null
      at CustomVariables.username [as setValueOf] (/root/bots/sogebot/src/bot/customvariables.js:339:55)
      at Socket.<anonymous> (/root/bots/sogebot/src/bot/widgets/custom_variables.ts:59:21)
} reason: TypeError: Cannot read property 'username' of null
```

**Comment by sogehige** [comment]
Possibly on widget change
