### ISSUE TITLE
Bot Cannot Start Properly Since Updating From 9.7.2 to 9.9.0

### ISSUE THREAD

**Issue by MoonlightAshe** [sogehige/sogeBot#2673]
### Expected behavior
Start completely.

### Actual behavior
Not starting completely. The main UI is there, but none of the modules are loaded.

### Steps to reproduce
Updating 9.7.2 to 9.9.0 is all I did to get this error

### Additional informations
Probably due to the command !botinfo I have set up, as the log entails. However, even if I delete the command before updating, this still occurs. Perhaps it is not being deleted in the database?

![image](https://user-images.githubusercontent.com/25715993/65812006-b92b4a00-e186-11e9-81bb-d5a7ca7c4c3d.png)

I test bots, so this command is used to tell people what bot I'm currently testing/using.

2019-09-27T23:26:04.119 | [32mENABLED[39m: Translations (metrics) 
2019-09-27T23:26:04.926 | WebPanel is available at http://localhost:20000 
2019-09-27T23:26:04.928 !!! ERROR !!! Error: Can't insert key !botinfo, it violates the unique constraint
    at _AVLTree.insert (/home/user/sogebot/node_modules/binary-search-tree/lib/avltree.js:273:19)
    at AVLTree.insert (/home/user/sogebot/node_modules/binary-search-tree/lib/avltree.js:307:27)
    at Index.insert (/home/user/sogebot/node_modules/nedb/lib/indexes.js:77:15)
    at Index.insertMultipleDocs (/home/user/sogebot/node_modules/nedb/lib/indexes.js:114:12)
    at Index.insert (/home/user/sogebot/node_modules/nedb/lib/indexes.js:69:33)
    at Index.reset (/home/user/sogebot/node_modules/nedb/lib/indexes.js:55:23)
    at /home/user/sogebot/node_modules/nedb/lib/datastore.js:107:21
    at Array.forEach (<anonymous>)
    at Datastore.resetIndexes (/home/user/sogebot/node_modules/nedb/lib/datastore.js:106:29)
    at /home/user/sogebot/node_modules/nedb/lib/persistence.js:293:23 {
  key: '!botinfo',
  errorType: 'uniqueViolated'
} 
2019-09-27T23:26:04.929 !!! ERROR !!! +------------------------------------------------------------------------------+ 
2019-09-27T23:26:04.929 !!! ERROR !!! | WORKER HAS UNEXPECTEDLY CRASHED                                              | 
2019-09-27T23:26:04.930 !!! ERROR !!! | PLEASE CHECK https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue | 
2019-09-27T23:26:04.930 !!! ERROR !!! | AND ADD logs/exceptions.log file to your report                              | 
2019-09-27T23:26:04.931 !!! ERROR !!! +------------------------------------------------------------------------------+ 
2019-09-27T23:26:08.182 | [33mCURRENCY:[39m fetching rates 
2019-09-27T23:26:08.982 | [33mCURRENCY:[39m fetched rates 
2019-09-27T23:26:14.713 | EMOTES: Fetching global emotes

**Comment by sogehige** [comment]
Please remove `systems.customcommands.count` collection and start bot

**Comment by MoonlightAshe** [comment]
That fixed the issue, thank you
