### ISSUE TITLE
Cannot start the bot.

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3013]
### Actual behavior
After updating to latest commit i cannot start the bot with followed error.
```
2019-11-21T11:19:23.587 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> Error: Cannot find module 'm3u8stream/lib/parse-time'
  Require stack:
  - /root/bots/test/node_modules/ytdl-core/lib/info-extras.js
  - /root/bots/test/node_modules/ytdl-core/lib/info.js
  - /root/bots/test/node_modules/ytdl-core/lib/index.js
  - /root/bots/test/dest/systems/songs.js
  - /root/bots/test/dest/commons.js
  - /root/bots/test/dest/permissions.js
  - /root/bots/test/dest/main.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
      at Function.Module._resolveFilename (/root/bots/test/node_modules/module-alias/index.js:49:29)
      at Function.Module._load (internal/modules/cjs/loader.js:677:27)
      at Module.require (internal/modules/cjs/loader.js:830:19)
      at require (internal/modules/cjs/helpers.js:68:18)
      at Object.<anonymous> (/root/bots/test/node_modules/ytdl-core/lib/info-extras.js:5:21)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/root/bots/test/node_modules/ytdl-core/lib/info-extras.js',
      '/root/bots/test/node_modules/ytdl-core/lib/info.js',
      '/root/bots/test/node_modules/ytdl-core/lib/index.js',
      '/root/bots/test/dest/systems/songs.js',
      '/root/bots/test/dest/commons.js',
      '/root/bots/test/dest/permissions.js',
      '/root/bots/test/dest/main.js'
    ]
  }
} reason: Error: Cannot find module 'm3u8stream/lib/parse-time'
Require stack:
- /root/bots/test/node_modules/ytdl-core/lib/info-extras.js
- /root/bots/test/node_modules/ytdl-core/lib/info.js
- /root/bots/test/node_modules/ytdl-core/lib/index.js
- /root/bots/test/dest/systems/songs.js
- /root/bots/test/dest/commons.js
- /root/bots/test/dest/permissions.js
- /root/bots/test/dest/main.js
```
### Additional informations

master https://github.com/sogehige/sogeBot/commit/90a6b1e404ba12d25c9ab2027529f6866a1c7767, postgres

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/pull/3014
