### ISSUE TITLE
tests only: various mysql errors during tests

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#3088]
```
query failed: SELECT `Permissions`.`id` AS `Permissions_id`, `Permissions`.`name` AS `Permissions_name`, `Permissions`.`order` AS `Permissions_order`, `Permissions`.`isCorePermission` AS `Permissions_isCorePermission`, `Permissions`.`isWaterfallAllowed` AS `Permissions_isWaterfallAllowed`, `Permissions`.`automation` AS `Permissions_automation`, `Permissions`.`userIds` AS `Permissions_userIds` FROM `permissions` `Permissions`
error: Error: Table 'sogebot.permissions' doesn't exist
    at Packet.asError (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/commands/command.js:28:26)
    at PoolConnection.handlePacket (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/runner/work/sogeBot/sogeBot/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  code: 'ER_NO_SUCH_TABLE',```

**Comment by sogehige** [comment]
I don't see errors anymore
