### ISSUE TITLE
TypeError: Class constructor Settings cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3113]
### Actual behavior
That message spamming in bot console.
```
2019-12-19T07:41:09.889 !!! ERROR !!! {"isDbConnected":true,"opts":{"name":"!game set","fnc":"setGame","permission":"b38c5adb-e912-47e3-937a-89fabd12393a","isHelper":false},"m":{"type":"core","name":"twitch","fnc":"setGame"}}
2019-12-19T07:41:09.889 !!! ERROR !!! TypeError: Class constructor Settings cannot be invoked without 'new'
at SelectQueryBuilder.QueryBuilder.createFromAlias (/app/src/query-builder/QueryBuilder.ts:528:67)
at SelectQueryBuilder.from (/app/src/query-builder/SelectQueryBuilder.ts:190:32)
at /app/src/bot/decorators.ts:321:8
at Generator.next (<anonymous>)
at /app/dest/decorators.js:8:71
at new Promise (<anonymous>)
at __awaiter (/app/dest/decorators.js:4:12)
at registerCommand (/app/dest/decorators.js:282:12)
at Timeout._onTimeout (/app/src/bot/decorators.ts:288:29)
at listOnTimeout (internal/timers.js:536:17)

```
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/5afe05b5e82f3f6473f49aebce8efbb130fa41b7

**Comment by sogehige** [comment]
Do you still see this issue with latest version?

**Comment by Banonevar** [comment]
Seems like not.

**Comment by Banonevar** [comment]
If i'll got same problem i'll reopen this issue.
