### ISSUE TITLE
Query failed for query-result-cache

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3213]
### Actual behavior
```
| query failed: UPDATE "query-result-cache" SET "identifier" = $1, "query" = $2, "time" = $3, "duration" = $4, "result" = $5 WHERE "query" = $6 -- PARAMETERS: [null,"SELECT \"permissions\".\"id\" AS \"permissions_id\", \"permissions\".\"name\" AS \"permissions_name\", \"permissions\".\"order\" AS \"permissions_order\", \"permissions\".\"isCorePermission\" AS \"permissions_isCorePermission\", \"permissions\".\"isWaterfallAllowed\" AS \"permissions_isWaterfallAllowed\", \"permissions\".\"automation\" AS \"permissions_automation\", \"permissions\".\"userIds\" AS \"permissions_userIds\" FROM \"permissions\" \"permissions\" ORDER BY \"permissions\".\"order\" DESC -- PARAMETERS: []",1580121639094,1000,"[{\"permissions_id\":\"0efd7b1c-e460-4167-8e06-8aaf2c170311\",\"permissions_name\":\"Viewers\",\"permissions_order\":5,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"viewers\",\"permissions_userIds\":\"\"},{\"permissions_id\":\"c168a63b-aded-4a90-978f-ed357e95b0d2\",\"permissions_name\":\"Followers\",\"permissions_order\":4,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"followers\",\"permissions_userIds\":\"\"},{\"permissions_id\":\"e3b557e7-c26a-433c-a183-e56c11003ab7\",\"permissions_name\":\"Subscribers\",\"permissions_order\":3,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"subscribers\",\"permissions_userIds\":\"\"},{\"permissions_id\":\"e8490e6e-81ea-400a-b93f-57f55aad8e31\",\"permissions_name\":\"VIP\",\"permissions_order\":2,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"vip\",\"permissions_userIds\":\"\"},{\"permissions_id\":\"b38c5adb-e912-47e3-937a-89fabd12393a\",\"permissions_name\":\"Moderators\",\"permissions_order\":1,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"moderators\",\"permissions_userIds\":\"\"},{\"permissions_id\":\"4300ed23-dca0-4ed9-8014-f5f2f7af55a9\",\"permissions_name\":\"Casters\",\"permissions_order\":0,\"permissions_isCorePermission\":true,\"permissions_isWaterfallAllowed\":true,\"permissions_automation\":\"casters\",\"permissions_userIds\":\"\"}]","SELECT \"permissions\".\"id\" AS \"permissions_id\", \"permissions\".\"name\" AS \"permissions_name\", \"permissions\".\"order\" AS \"permissions_order\", \"permissions\".\"isCorePermission\" AS \"permissions_isCorePermission\", \"permissions\".\"isWaterfallAllowed\" AS \"permissions_isWaterfallAllowed\", \"permissions\".\"automation\" AS \"permissions_automation\", \"permissions\".\"userIds\" AS \"permissions_userIds\" FROM \"permissions\" \"permissions\" ORDER BY \"permissions\".\"order\" DESC -- PARAMETERS: []"]
| error: error: deadlock detected
|     at Connection.parseE (/app/node_modules/pg/lib/connection.js:606:11)
|     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:403:19)
|     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:123:22)
|     at Socket.emit (events.js:219:5)
|     at addChunk (_stream_readable.js:332:12)
|     at readableAddChunk (_stream_readable.js:307:11)
|     at Socket.Readable.push (_stream_readable.js:241:10)
|     at TCP.onStreamRead (internal/stream_base_commons.js:185:23) {
|   name: 'error',
|   length: 361,
|   severity: 'ERROR',
|   code: '40P01',
|   detail: 'Process 27724 waits for ShareLock on transaction 2412902156; blocked by process 27726.\n' +
|     'Process 27726 waits for ShareLock on transaction 2412902179; blocked by process 27724.',
|   hint: 'See server log for query details.',
|   position: undefined,
|   internalPosition: undefined,
|   internalQuery: undefined,
|   where: 'while rechecking updated tuple (40,5) in relation "query-result-cache"',
|   schema: undefined,
|   table: undefined,
|   column: undefined,
|   dataType: undefined,
|   constraint: undefined,
|   file: 'deadlock.c',
|   line: '1146',
|   routine: 'DeadLockReport'
| }
```

I don't know what can cause that and what of reason of that.
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/60f3bfd16c62d9cfb0e3f0a55a3e3f527b81d7e5

**Comment by sogehige** [comment]
hint: 'See server log for query details.',
