### ISSUE TITLE
!you expects error

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3316]
### Actual behavior
```
2020-03-04T12:40:31.781 <<< !me [p0ooo0h]
2020-03-04T12:40:32.647 !!! ERROR !!! Error: <username>
at Expects.checkText (/app/src/bot/expects.ts:130:15)
at Expects.username (/app/src/bot/expects.ts:419:12)
at Expects.exec (/app/src/bot/expects.ts:33:19)
at Expects.toArray (/app/src/bot/expects.ts:146:12)
at UserInfo.<anonymous> (/app/src/bot/systems/userinfo.ts:284:64)
at Generator.next (<anonymous>)
at /app/dest/systems/userinfo.js:17:71
at new Promise (<anonymous>)
at __awaiter (/app/dest/systems/userinfo.js:13:12)
at UserInfo.showStats (/app/dest/systems/userinfo.js:271:16)
```
at !you command usage w/o param
### Steps to reproduce
use `!you` in chat.
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/86c56515c8d5d43dcb7ba1a6f193cd617edb88be

**Comment by sogehige** [comment]
You mean !stats command?

**Comment by Banonevar** [comment]
> You mean !stats command?

Oh, yes, sorry, i just have renamed it.
