### ISSUE TITLE
Cannot read property 'name' of undefined if bot has custom written system

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3366]
### Actual behavior
```
| 2020-03-17T08:00:48.490 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'name' of undefined
 at /app/src/bot/watchers.ts:81:57
at Array.find (<anonymous>)
 at Object.<anonymous> (/app/src/bot/watchers.ts:81:33)
at Generator.next (<anonymous>)
 at /app/dest/watchers.js:8:71
 at new Promise (<anonymous>)
 at __awaiter (/app/dest/watchers.js:4:12)
 at Object.check (/app/dest/watchers.js:38:16)
 at Timeout._onTimeout (/app/src/bot/watchers.ts:20:21)
at listOnTimeout (internal/timers.js:549:17)
} reason: TypeError: Cannot read property 'name' of undefined
```
### Steps to reproduce
i don't know why it happens. 
It's just spamming in bot console each second. 
### Additional informations

master https://github.com/sogehige/sogeBot/commit/cb6ad88b45daac2a8f54972bfe7c505495ece00c

**Comment by Banonevar** [comment]
Also on the same bot i cannot open dashboard. It can be related, right?

**Comment by Banonevar** [comment]
Hm, i noticed, thats because i has custom system.
```ts
'use strict';

import System from './_interface';
import _ from 'lodash';
import { command } from '../decorators';
import { sendMessage } from '../commons';
import { getRepository } from 'typeorm';
import { User } from '../database/entity/user';


class XaunBeact extends System {
  constructor() {
    super();
  }

  @command('!монетка')
  async coin(opts: CommandOptions) {
    const example = '!монетка орёл 500';
    const user = await getRepository(User).findOne({ userId: opts.sender.userId });

    if (!user) {
      return;
    }

    const args = opts.parameters.split(' ');
    if (args.length < 2) {
      return sendMessage(`${opts.sender.displayName} недостаточно аргументов! Для того что бы кинуть монетку напиши ${example}`, opts.sender);
    }

    const bet = Number(args[1]);

    if (isNaN(bet)) {
      return sendMessage(`${opts.sender.displayName} неправильное использование. Для того что бы кинуть монетку напиши ${example}`, opts.sender);
    }
    if (user.points < bet) {
      return sendMessage(`${opts.sender.displayName} нехваточка, браток.`, opts.sender);
    }
    const acceptedArgs = ['орёл', 'решка'];
    const type = args[0];
    if (!acceptedArgs.filter((o) => o === type).length) {
      return sendMessage(`${opts.sender.displayName} не понимаю чё ты там написал. Пиши орёл или решка.`, opts.sender);
    }

    const winArg = _.sample(acceptedArgs);

    if (winArg === type) {
      await getRepository(User).increment({ userId: opts.sender.userId }, 'points', bet);
      return sendMessage(`${opts.sender.displayName} ты победил, удача была на твоей стороне.`, opts.sender);
    } else {
      await getRepository(User).decrement({ userId: opts.sender.userId }, 'points', bet);
      return sendMessage(`${opts.sender.displayName} прости, но тут ${winArg}`, opts.sender);
    }
  }
}

export default new XaunBeact();
```
Do that system need to be rewritten?

**Comment by Banonevar** [comment]
Another my bot with another custom system has same issue now. Thats exactly applies to custom systems. :thinking:

**Comment by sogehige** [comment]
Working for me ok

```
> sogebot@10.10.0-SNAPSHOT start /home/soge/_WORK/sogeBot
> cross-env NODE_ENV=production node --always_compact --optimize_for_size --gc_interval=100 --max_old_space_size=920 -r source-map-support/register  ./dest/main || true

███████╗ ██████╗  ██████╗ ███████╗██████╗  ██████╗ ████████╗     ██╗ ██████╗    ██╗ ██████╗     ██████╗       ██╗  ██╗ ██████╗  █████╗ ██████╗ ██████╗  █████╗  ██████╗ 
██╔════╝██╔═══██╗██╔════╝ ██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝    ███║██╔═████╗  ███║██╔═████╗   ██╔═████╗      ██║  ██║██╔════╝ ██╔══██╗██╔══██╗╚════██╗██╔══██╗██╔═████╗
███████╗██║   ██║██║  ███╗█████╗  ██████╔╝██║   ██║   ██║       ╚██║██║██╔██║  ╚██║██║██╔██║   ██║██╔██║█████╗███████║███████╗ ╚█████╔╝██████╔╝ █████╔╝╚██████║██║██╔██║
╚════██║██║   ██║██║   ██║██╔══╝  ██╔══██╗██║   ██║   ██║        ██║████╔╝██║   ██║████╔╝██║   ████╔╝██║╚════╝╚════██║██╔═══██╗██╔══██╗██╔══██╗██╔═══╝  ╚═══██║████╔╝██║
███████║╚██████╔╝╚██████╔╝███████╗██████╔╝╚██████╔╝   ██║        ██║╚██████╔╝██╗██║╚██████╔╝██╗╚██████╔╝           ██║╚██████╔╝╚█████╔╝██████╔╝███████╗ █████╔╝╚██████╔╝
╚══════╝ ╚═════╝  ╚═════╝ ╚══════╝╚═════╝  ╚═════╝    ╚═╝        ╚═╝ ╚═════╝ ╚═╝╚═╝ ╚═════╝ ╚═╝ ╚═════╝            ╚═╝ ╚═════╝  ╚════╝ ╚═════╝ ╚══════╝ ╚════╝  ╚═════╝ 
                                                                                                                                                                        


2020-03-17T11:42:06.666 | Bot is starting up
2020-03-17T11:42:06.823 | Initialized SQLite3 database (/home/soge/_WORK/sogeBot/sogebot.db)
2020-03-17T11:42:10.819 | CURRENCY: fetching rates
2020-03-17T11:42:10.983 | CURRENCY: fetched rates
2020-03-17T11:42:16.610 | EMOTES: Fetching global emotes
2020-03-17T11:42:17.455 | EMOTES: Fetched global emotes
2020-03-17T11:42:21.598 !!! ERROR !!! SONGS: Missing YouTube API key.
2020-03-17T11:42:21.704 | ENABLED: Spotify (integrations)
2020-03-17T11:42:21.705 | SPOTIFY: Client connected to service
2020-03-17T11:42:21.734 | ENABLED: Songs (systems)
2020-03-17T11:42:21.820 |! Bot je nyni prepnuty do cestiny
2020-03-17T11:42:22.174 | WebPanel is available at http://localhost:20000
2020-03-17T11:42:22.919 | Channel ID set to 96965261
2020-03-17T11:42:22.920 | TMI: bot is reconnecting
2020-03-17T11:42:22.921 | TMI: broadcaster is reconnecting
2020-03-17T11:42:24.362 | TMI: bot joined channel soge
2020-03-17T11:42:24.414 | TMI: broadcaster joined channel soge
2020-03-17T11:42:24.965 | Title/game force enabled => Rocket League | Rakeťák | Do nekonečna a ještě dál!
2020-03-17T11:42:37.226 | ENABLED: Raffles (systems)
2020-03-17T11:42:37.229 | ENABLED: Scrim (systems)
2020-03-17T11:42:37.229 | ENABLED: Timers (systems)
2020-03-17T11:42:37.229 | ENABLED: Top (systems)
2020-03-17T11:42:37.229 | ENABLED: UserInfo (systems)
2020-03-17T11:42:37.230 | ENABLED: Duel (games)
2020-03-17T11:42:37.230 | ENABLED: FightMe (games)
2020-03-17T11:42:37.230 | ENABLED: Gamble (games)
2020-03-17T11:42:37.230 | ENABLED: Heist (games)
2020-03-17T11:42:37.231 | ENABLED: Roulette (games)
2020-03-17T11:42:37.231 | ENABLED: Seppuku (games)
2020-03-17T11:42:37.231 | DISABLED: Donationalerts (integrations)
2020-03-17T11:42:37.231 | ENABLED: Alias (systems)
2020-03-17T11:42:37.232 | ENABLED: Points (systems)
2020-03-17T11:42:37.232 | ENABLED: Bets (systems)
2020-03-17T11:42:37.232 | ENABLED: HowLongToBeat (systems)
2020-03-17T11:42:37.232 | ENABLED: Keywords (systems)
2020-03-17T11:42:37.232 | ENABLED: ChannelName (systems)
2020-03-17T11:42:37.233 | ENABLED: Checklist (systems)
2020-03-17T11:42:37.233 | ENABLED: Commercial (systems)
2020-03-17T11:42:37.233 | ENABLED: Moderation (systems)
2020-03-17T11:42:37.233 | DISABLED: PhillipsHue (integrations)
2020-03-17T11:42:37.234 | PHILLIPSHUE: Not connected to api
2020-03-17T11:42:37.234 | DISABLED: Qiwi (integrations)
2020-03-17T11:42:37.234 | DISABLED: StreamElements (integrations)
2020-03-17T11:42:37.235 | ENABLED: Streamlabs (integrations)
2020-03-17T11:42:37.240 | ENABLED: Price (systems)
2020-03-17T11:42:37.240 | ENABLED: Polls (systems)
2020-03-17T11:42:37.241 | ENABLED: Queue (systems)
2020-03-17T11:42:37.241 | DISABLED: TipeeeStream (integrations)
2020-03-17T11:42:37.241 | DISABLED: Twitter (integrations)
2020-03-17T11:42:37.242 | TWITTER: Client disconnected from service
2020-03-17T11:42:37.242 | ENABLED: Ranks (systems)
2020-03-17T11:42:37.242 | ENABLED: CustomCommands (systems)
2020-03-17T11:42:37.242 | ENABLED: Cooldown (systems)
2020-03-17T11:42:37.242 | ENABLED: Highlights (systems)
2020-03-17T11:42:37.243 | ENABLED: Quotes (systems)
2020-03-17T11:42:38.778 | STREAMLABS: Successfully connected socket to service
```

![9eb4fa86-710d-4a67-a3c3-4000c7f56726](https://user-images.githubusercontent.com/19549652/76849581-f45d2a80-6845-11ea-937b-b8d3ffb85101.png)

**Comment by Banonevar** [comment]
Maybe pg only related?

**Comment by Banonevar** [comment]
After update to latest master https://github.com/sogehige/sogeBot/commit/69364a0cbe18bdbb78d9f6fa004c647233aa5479
```
2020-03-17T13:01:57.560 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'name' of undefined
at /app/src/bot/watchers.ts:76:57
at Array.find (<anonymous>)
at Object.<anonymous> (/app/src/bot/watchers.ts:76:33)
at Generator.next (<anonymous>)
at /app/dest/watchers.js:8:71
at new Promise (<anonymous>)
at __awaiter (/app/dest/watchers.js:4:12)
at Object.check (/app/dest/watchers.js:38:16)
at Timeout._onTimeout (/app/src/bot/watchers.ts:20:21)
at listOnTimeout (internal/timers.js:549:17)
} reason: TypeError: Cannot read property 'name' of undefined
```

**Comment by sogehige** [comment]
Well, its still same error, I cannot reproduce that.

**Comment by Banonevar** [comment]
I know, it's kind of annoying for you, but i can give you db data dump, or even db connection details, if you want.

**Comment by Banonevar** [comment]
Hm, even without custom system got same error.

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/blob/master/src/bot/watchers.ts#L18

You can try to add 
```javascript
setTimeout(() => {
  setInterval(() => {
    if (isDbConnected) {
      VariableWatcher.check();
    }
  }, 1000);
}, 60000)
```

**Comment by Banonevar** [comment]
Same behavior for me.

**Comment by Banonevar** [comment]
That commit fixed the issue.
