### ISSUE TITLE
streamlabs test donation error

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#3565]
sogebot_1  | 2020-04-19T13:12:10.677 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
sogebot_1  |   <rejected> QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: user_tip.currency
sogebot_1  |       at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
sogebot_1  |       at Statement.handler (/app/src/driver/sqlite/SqliteQueryRunner.ts:53:26) {
sogebot_1  |     errno: 19,
sogebot_1  |     code: 'SQLITE_CONSTRAINT',
sogebot_1  |     query: 'INSERT INTO "user_tip"("id", "amount", "sortAmount", "exchangeRates", "currency", "message", "tippedAt", "userUserId") VALUES (NULL, ?, ?, ?, NULL, ?, ?, ?)',
sogebot_1  |     parameters: [
sogebot_1  |       5,
sogebot_1  |       5,
sogebot_1  |       '{"AUD":15.896,"BGN":13.896,"BRL":4.783,"CAD":17.777,"CHF":25.833,"CNY":3.536,"CZK":1,"DKK":3.641,"EUR":27.165,"GBP":31.231,"HKD":3.227,"HRK":3.588,"HUF":0.077,"IDR":0.002,"ILS":6.967,"INR":0.327,"ISK":0.174,"JPY":0.232,"KRW":0.021,"MXN":1.041,"MYR":5.723,"NOK":2.407,"NZD":15.056,"PHP":0.491,"PLN":6.012,"RON":5.618,"RUB":0.338,"SEK":2.503,"SGD":17.581,"THB":0.769,"TRY":3.622,"USD":25.009,"ZAR":1.334,"XDR":34.134}',
sogebot_1  |       'test',
sogebot_1  |       1587301860000,
sogebot_1  |       12427
sogebot_1  |     ]
sogebot_1  |   }
sogebot_1  | } reason: QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: user_tip.currency

**Comment by sogehige** [comment]
Not an issue of sogebot, when manually adding new donation, formatted_amount from streamlabs get back as `undefined5.0000`
