### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#3703]
Random crash overnight. No actions were taken during this as I was asleep. Here is the output from the console. Attached debug file.

```
2020-05-10T08:58:11.313 !!! ERROR !!! Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  config: {
    url: 'https://streamlabs.com/api/v1.0/donations?access_token=[ACCESS_TOKEN]&after=130359381',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/v1.0/donations?access_token=[ACCESS_TOKEN]&after=130359381',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'streamlabs.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/v1.0/donations',
      search: '?access_token=[ACCESS_TOKEN]&after=130359381'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/v1.0/donations?access_token=[ACCESS_TOKEN]&after=130359381 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: streamlabs.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v1.0/donations?access_token=[ACCESS_TOKEN]&after=130359381',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://streamlabs.com/api/v1.0/donations?access_token=[ACCESS_TOKEN]&after=130359381',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}

<--- Last few GCs --->

[5432:000000000041CBB0] 259521660 ms: Scavenge 542.4 (544.6) -> 541.9 (544.6) MB, 5.9 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure
[5432:000000000041CBB0] 259521700 ms: Scavenge 542.5 (544.6) -> 542.5 (545.1) MB, 9.6 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure
[5432:000000000041CBB0] 259521724 ms: Scavenge 542.9 (545.1) -> 542.8 (545.6) MB, 7.8 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.

<--- Last few GCs --->

[5432:000000000041CBB0] 259521660 ms: Scavenge 542.4 (544.6) -> 541.9 (544.6) MB, 5.9 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure
[5432:000000000041CBB0] 259521700 ms: Scavenge 542.5 (544.6) -> 542.5 (545.1) MB, 9.6 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure
[5432:000000000041CBB0] 259521724 ms: Scavenge 542.9 (545.1) -> 542.8 (545.6) MB, 7.8 / 0.0 ms  (average mu = 0.571, current mu = 0.579) allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sogebot@11.0.0 start: `cross-env NODE_ENV=production node --experimental-report --report-on-fatalerror --report-directory=./logs/ --always_compact --optimize_for_size --gc_interval=100 --max_old_space_size=920 -r source-map-support/register  ./dest/main || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sogebot@11.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[USER]\AppData\Roaming\npm-cache\_logs\2020-05-10T15_58_35_570Z-debug.log
```

```
2020-05-10T09:42:17.335 <<< !_debug [[CHANNELNAME]]
2020-05-10T09:42:17.662 DEBUG: * ======= COPY DEBUG MESSAGE FROM HERE =======
2020-05-10T09:42:17.662 DEBUG: * GENERAL      | OS: npm/6.14.4 node/v12.16.2 win32 x64
2020-05-10T09:42:17.728 DEBUG: *              | Bot version: 11.0.0
2020-05-10T09:42:17.728 DEBUG: *              | DB: sqlite
2020-05-10T09:42:17.748 DEBUG: *              | HEAP: 72.83 MB
2020-05-10T09:42:17.748 DEBUG: *              | Uptime: 00:05:11
2020-05-10T09:42:17.749 DEBUG: *              | Language: en
2020-05-10T09:42:17.749 DEBUG: *              | Mute: false
2020-05-10T09:42:17.750 DEBUG: * SYSTEMS      | -Songs, -Highlights, -Points, Alias, -Bets, -Checklist, -Commercial, -Ranks, CustomCommands, -Cooldown, HowLongToBeat, -Keywords, -Moderation, -Polls, -Price, -Queue, -Quotes, Raffles, -Scrim, Timers, -Top, UserInfo
2020-05-10T09:42:17.750 DEBUG: * GAMES        | -Duel, -FightMe, -Gamble, -Heist, -Roulette, -Seppuku
2020-05-10T09:42:17.754 DEBUG: * INTEGRATIONS | -Spotify, -Discord, -ResponsiveVoice, -Donationalerts, -PhillipsHue, -Qiwi, -StreamElements, Streamlabs, -TipeeeStream, -Twitter
2020-05-10T09:42:17.754 DEBUG: * WIDGETS      | chat, eventlist
2020-05-10T09:42:17.754 DEBUG: * OAUTH        | BOT true | BROADCASTER true
2020-05-10T09:42:17.754 DEBUG: * ======= END OF DEBUG MESSAGE =======
2020-05-10T09:42:17.800 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
      at TMI.<anonymous> (C:\[CHANNELNAME]\sogeBot-11.0.0\src\bot\tmi.ts:813:37)
      at Generator.next (<anonymous>)
      at fulfilled (C:\[CHANNELNAME]\sogeBot-11.0.0\dest\tmi.js:14:58)
} reason: TypeError: Cannot read property 'length' of undefined

```
[debug.txt](https://github.com/sogehige/sogeBot/files/4606644/debug.txt)

**Comment by sogehige** [comment]
Thanks for report, not sure if I will be able to do anything with that as I don't have reported any heap issues.

I will fix debug tmi error.

Issues:
1. Streamlabs had some api issues, should be OK now
2. you are using node 12.16.2, I would recommend to update to 12.16.3 LTS or latest node 14.2.0 (which I would recommend)
3. Heap issues are hard to reproduce, until I've got more reports about heap issues, I tend to ignore it as they are super hard and time consuming to fix.

**Comment by chiefstank** [comment]
Okay. At some point I'll try and upgrade node. My stream is 24/7 so I limit what is installed/upgraded while it's live. Thanks!

**Comment by sogehige** [comment]
Yeah it also depends on how long you are online. That would be good to know as well, but usually longer bot is running, this might just happen as I cannot possibly be able to find every heap issues unfortunately. Also there is configuration to stop bot each x hours to eliminate these issues during stream, but if you are online all time that wouldn't help you much :)

**Comment by chiefstank** [comment]
Just had another crash. It typically runs indefinitely, but in this instance it had only been about 24 hours since the last crash. FWIW, didn't get any crashes in 10.x.x.

I did see that option to stop the bot which I'd like to use but unless it starts it back up as well, I can't at this time.  

Here is the debug again just because. ;)

[crash.txt](https://github.com/sogehige/sogeBot/files/4610744/crash.txt)

**Comment by sogehige** [comment]
Can you share your report file in logs?

Also you can try to set higher --max-old-space-size in package.json

https://github.com/sogehige/sogeBot/blob/47a2595a39fb51d731dd85282c2686cafbc6a647/package.json#L84
```
"start": "cross-env NODE_ENV=production node --experimental-report --report-on-fatalerror --report-directory=./logs/ --always_compact --optimize_for_size --gc_interval=100 --max_old_space_size=1840 -r source-map-support/register  ./dest/main || true",
```

**Comment by sogehige** [comment]
On master after https://github.com/sogehige/sogeBot/pull/3716 or next release we will be able to use e.g.

`NODE_OPTIONS=--max_old_space_size=4096 npm start`

To dynamically update this node option without need of updating package.json

**Comment by sogehige** [comment]
Closing as we don't have any followup for month
