### ISSUE TITLE
Emote Kappa_/543\ Makes bot crash

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3762]
### Actual behavior
When users in chat using `Kappa_/543\` emote, then bot crashing 
### Steps to reproduce
```
2020-05-16T15:50:47.632 !!! ERROR !!! ParseError: [TwitchJS] Parse error encountered [Chat]
_raw: '@badge-info=;badges=glhf-pledge/1;color=;display-name=zill0fn;emote-only=1;emotes=25_/543:0-9;flags=;id=1badbfd7-5b60-4983-9250-6cd58a63217c;mod=0;room-id=139336353;subscriber=0;tmi-sent-ts=1589644243163;turbo=0;user-id=184770490;user-type= :zill0fn!zill0fn@zill0fn.tmi.twitch.tv PRIVMSG #channel :Kappa_/543\r\n',
```

**Comment by sogehige** [comment]
What is that Kappa_/543\? I don't see this emote anywhere

**Comment by Banonevar** [comment]
Yea, me to, but it exists, trust me. It some rmote from not existed channel, with huge image size... It's not bttv, it's a twitch emote. But you can't find it.

**Comment by Banonevar** [comment]
For some reason not all users can use that emote.

**Comment by sogehige** [comment]
I am not 100% sure how we can fix it and this is probably twitchjs issue and not bot persay

**Comment by Banonevar** [comment]
Possibly patch twitch js.

Just do not crash on parsing error.

**Comment by sogehige** [comment]
Are there any more errors?

**Comment by Banonevar** [comment]
@sogehige 
```
 "javascriptStack": {
    "message": "Error: [TwitchJS] Parse error encountered [Chat]",
    "stack": [
      "at ParseError.ChatError [as constructor] (/app/node_modules/twitch-js/src/Chat/Errors.ts:10:5)",
      "at new ParseError (/app/node_modules/twitch-js/src/Chat/Errors.ts:33:5)",
      "at Client._handleMessage (/app/node_modules/twitch-js/src/Chat/Client.ts:190:28)",
      "at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)",
      "at WebSocket.emit (events.js:315:20)",
      "at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:800:20)",
      "at Receiver.emit (events.js:315:20)",
      "at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:423:14)",
      "at Receiver.getData (/app/node_modules/ws/lib/receiver.js:353:17)",
      "at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:139:22)",
      "at Receiver._write (/app/node_modules/ws/lib/receiver.js:74:10)",
      "at writeOrBuffer (_stream_writable.js:353:12)",
      "at Receiver.Writable.write (_stream_writable.js:303:12)",
      "at TLSSocket.socketOnData (/app/node_modules/ws/lib/websocket.js:875:35)",
      "at TLSSocket.emit (events.js:315:20)",
      "at addChunk (_stream_readable.js:302:12)",
      "at readableAddChunk (_stream_readable.js:278:9)",
      "at TLSSocket.Readable.push (_stream_readable.js:217:10)"
    ]
  },
```

**Comment by sogehige** [comment]
Anything related to bot crash? This shouldn't crash bot.

**Comment by Banonevar** [comment]
But it crashed.

I can share whole `uncaughtException` in discord.
