### ISSUE TITLE
Custom variable GET URL returns error 500

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#4083]
my apologies if it's already been fixed, i'm still on 11.8.4 and can't upgrade at the moment. i have a custom variable that simply returns true/false. the custom variable has a GET URL enabled on it so i can retrieve the value through GET. everytime i try to access it shows error 500 with this in console. 

![2020-08-30 18_50_30-11 8 4](https://user-images.githubusercontent.com/6421187/91675579-bac96480-eaf1-11ea-96dc-63ce5dd74808.png)

```
2020-08-31T09:06:51.601 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'sender' of undefined
      at CustomVariables.<anonymous> (C:\sogeBot-11.12.3\src\bot\customvariables.ts:375:16)
      at Generator.next (<anonymous>)
      at fulfilled (C:\sogeBot-11.12.3\dest\customvariables.js:5:58)
} reason: TypeError: Cannot read property 'sender' of undefined
```

```
2020-08-31T09:07:16.321 DEBUG: * ======= COPY DEBUG MESSAGE FROM HERE =======
2020-08-31T09:07:16.322 DEBUG: * GENERAL      | OS: npm/6.14.4 node/v12.16.2 win32 x64
2020-08-31T09:07:16.406 DEBUG: *              | Bot version: 11.12.3
2020-08-31T09:07:16.406 DEBUG: *              | DB: sqlite
2020-08-31T09:07:16.407 DEBUG: *              | HEAP: 74.65 MB
2020-08-31T09:07:16.407 DEBUG: *              | Uptime: 00:02:23
2020-08-31T09:07:16.407 DEBUG: *              | Language: en
2020-08-31T09:07:16.407 DEBUG: *              | Mute: false
2020-08-31T09:07:16.407 DEBUG: * SYSTEMS      | -Songs, -Highlights, -Points, -Price, -Ranks, CustomCommands, Alias, -Bets, -Checklist, -Commercial, -Cooldown, -HowLongToBeat, -Keywords, -Moderation, -Polls, -Queue, -Quotes, Raffles, -Scrim, Timers, -Top, UserInfo
2020-08-31T09:07:16.408 DEBUG: * GAMES        | -Duel, -FightMe, -Gamble, -Heist, -Roulette, -Seppuku
2020-08-31T09:07:16.408 DEBUG: * INTEGRATIONS | -LastFM, -Spotify, Discord, -ResponsiveVoice, -Donationalerts, -PhillipsHue, -Qiwi, -StreamElements, Streamlabs, -TipeeeStream, -Twitter
2020-08-31T09:07:16.408 DEBUG: * WIDGETS      | eventlist, raffles
2020-08-31T09:07:16.408 DEBUG: * OAUTH        | BOT true | BROADCASTER true
2020-08-31T09:07:16.408 DEBUG: * ======= END OF DEBUG MESSAGE =======
```

**Comment by sogehige** [comment]
Good catch it seems to be busted on scripts variables
