### ISSUE TITLE
spotify bot crash

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#4312]
```
2020-11-12T17:10:18.001 !!! ERROR !!! TypeError: Cannot read property 'body' of undefined
    at _toError (/home/soge/_WORK/sogeBot/node_modules/spotify-web-api-node/src/http-manager.js:34:23)
    at fn (/home/soge/_WORK/sogeBot/node_modules/spotify-web-api-node/src/http-manager.js:71:25)
    at Request.callback (/home/soge/_WORK/sogeBot/node_modules/superagent/src/node/index.js:902:3)
    at ClientRequest.<anonymous> (/home/soge/_WORK/sogeBot/node_modules/superagent/src/node/index.js:814:10)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by sogehige** [comment]
Not sure where this is coming from as we have everythin in try/catch and this might be issue in spotify lib itself

**Comment by sogehige** [comment]
=> https://github.com/thelinmichael/spotify-web-api-node/pull/341

**Comment by sogehige** [comment]
Adding patch
