### ISSUE TITLE
error parsing subscription event

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#4315]
```2020-11-12T21:47:00.094 !!! ERROR !!! Error parsing subscription event
2020-11-12T21:47:00.101 !!! ERROR !!! {
  _raw: '@badge-info=;badges=;color=;display-name=testuser;emotes=;flags=;id=805a43b7-5303-41c7-bd1c-42f5b62e3836;login=testuser;mod=0;msg-id=subgift;msg-param-gift-months=1;msg-param-months=1;msg-param-origin-id=da\\s39\\sa3\\see\\s5e\\s6b\\s4b\\s0d\\s32\\s55\\sbf\\sef\\s95\\s60\\s18\\s90\\saf\\sd8\\s07\\s09;msg-param-recipient-display-name=lafemmedechowh1;msg-param-recipient-id=517980950;msg-param-recipient-user-name=lafemmedechowh1;msg-param-sender-count=0;msg-param-sub-plan-name=Abonnement\\sTier\\s1\\s—\\sSqueezie;msg-param-sub-plan=1000;room-id=52130765;subscriber=0;system-msg=testuser\\sgifted\\sa\\sTier\\s1\\ssub\\sto\\slafemmedechowh1!;tmi-sent-ts=1605214020175;user-id=123456;user-type= :tmi.twitch.tv USERNOTICE #squeezie',
  timestamp: 2020-11-12T20:47:00.175Z,
  command: 'USERNOTICE',
  event: 'SUBSCRIPTION_GIFT',
  channel: '#squeezie',
  username: 'testuser',
  isSelf: false,
  tags: {
    badgeInfo: '',
    badges: { '': undefined },
    color: '',
    displayName: 'testuser',
    emotes: [],
    flags: '',
    id: '805a43b7-5303-41c7-bd1c-42f5b62e3836',
    login: 'testuser',
    mod: '0',
    msgId: 'subgift',
    msgParamGiftMonths: '1',
    msgParamMonths: '1',
    msgParamOriginId: 'da 39 a3 ee 5e 6b 4b 0d 32 55 bf ef 95 60 18 90 af d8 07 09',
    msgParamRecipientDisplayName: 'asdsadsadsa',
    msgParamRecipientId: '517980950',
    msgParamRecipientUserName: 'asdadasdsad',
    msgParamSenderCount: '0',
    msgParamSubPlanName: 'Abonnement Tier 1 — Squeezie',
    msgParamSubPlan: '1000',
    roomId: '52130765',
    subscriber: '0',
    systemMsg: 'testuser gifted a Tier 1 sub to asdsadsad!',
    tmiSentTs: '1605214020175',
    userId: '123456',
    userType: '',
    bits: undefined,
    emoteSets: [],
    username: 'testuser'
  },
  message: undefined,
  parameters: {
    giftMonths: '1',
    months: 1,
    originId: 'da 39 a3 ee 5e 6b 4b 0d 32 55 bf ef 95 60 18 90 af d8 07 09',
    recipientDisplayName: 'lafemmedechowh1',
    recipientId: '517980950',
    recipientUserName: 'lafemmedechowh1',
    senderCount: 0,
    subPlanName: 'Abonnement Tier 1 — Squeezie',
    subPlan: '1000'
  },
  systemMessage: 'testuser gifted a Tier 1 sub to asdsadsa!'
}
2020-11-12T21:47:00.106 !!! ERROR !!! QueryFailedError: SqliteError: NOT NULL constraint failed: user.subscribeCumulativeMonths
    at new QueryFailedError (E:\_GIT\sogeBot\src\error\QueryFailedError.ts:9:9)
    at BetterSqlite3QueryRunner.<anonymous> (E:\_GIT\sogeBot\src\driver\better-sqlite3\BetterSqlite3QueryRunner.ts:103:19)
    at step (E:\_GIT\sogeBot\node_modules\tslib\tslib.js:141:27)
    at Object.next (E:\_GIT\sogeBot\node_modules\tslib\tslib.js:122:57)
    at fulfilled (E:\_GIT\sogeBot\node_modules\tslib\tslib.js:112:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)```

**Comment by sogehige** [comment]
This should go through subgift() but not sure why it went to subscription()
