### ISSUE TITLE
Cannot find Database

### ISSUE THREAD

**Issue by katasuno** [sogehige/sogeBot#4510]
### Expected behavior
There is a line in cleanup.js like const Database = require ('../ dest / databases / database'), but there is no folder in the form of databases in the dest folder.

### Additional informations

Error: Cannot find module '../dest/databases/database'
Require stack:
- C:\Users\Erdinc\Desktop\chat\tools\cleanup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Erdinc\Desktop\chat\tools\cleanup.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Erdinc\\Desktop\\chat\\tools\\cleanup.js' ]
}
![image](https://user-images.githubusercontent.com/62215083/103708172-1b494080-4fc1-11eb-8281-4ee1fc8e54c6.png)

**Comment by sogehige** [comment]
This file should be deleted. Why are yo trying to run it?
