### ISSUE TITLE
Bot won't connect, can't refresh access token, request failed with error 403

### ISSUE THREAD

**Issue by Deanosim** [sogehige/sogeBot#4674]
### Expected behavior
For the bot to connect
### Actual behavior
Doesn't connect
### Steps to reproduce
install bot, add oauth codes and save.
### Additional informations

Can't run !_debug because it won't connect, but heres my sogebot.log
2021-03-18T05:51:14.356 | Bot is starting up (NodeJS: 14.16.0)
2021-03-18T05:51:17.511 | Initialized SQLite3 database (/app/shared/sogebot.db)
2021-03-18T05:51:18.378 | Bot timezone set to Australia/Sydney
2021-03-18T05:51:29.579 | No certificates were provided, serving only HTTP.
2021-03-18T05:51:30.125 | WebPanel is available at http://localhost:20000
2021-03-18T05:51:30.606 | ENABLED: Points (systems)
2021-03-18T05:51:45.582 |! Bot language is currently set to english
2021-03-18T05:52:05.145 | CURRENCY: fetching rates
2021-03-18T05:52:05.193 | ENABLED: Ranks (systems)
2021-03-18T05:52:05.199 | ENABLED: CustomCommands (systems)
2021-03-18T05:52:05.202 | ENABLED: Alias (systems)
2021-03-18T05:52:05.206 | DISABLED: Discord (integrations)
2021-03-18T05:52:05.208 | DISABLED: LastFM (integrations)
2021-03-18T05:52:05.209 | DISABLED: Spotify (integrations)
2021-03-18T05:52:05.209 | SPOTIFY: Client disconnected from service
2021-03-18T05:52:05.211 | ENABLED: Songs (systems)
2021-03-18T05:52:05.218 | ENABLED: Highlights (systems)
2021-03-18T05:52:05.231 | ENABLED: Bets (systems)
2021-03-18T05:52:05.235 | ENABLED: Checklist (systems)
2021-03-18T05:52:05.236 | ENABLED: Commercial (systems)
2021-03-18T05:52:05.237 | ENABLED: Cooldown (systems)
2021-03-18T05:52:05.240 | ENABLED: HowLongToBeat (systems)
2021-03-18T05:52:05.242 | ENABLED: Keywords (systems)
2021-03-18T05:52:05.245 | ENABLED: Levels (systems)
2021-03-18T05:52:05.251 | ENABLED: Moderation (systems)
2021-03-18T05:52:05.253 | ENABLED: Polls (systems)
2021-03-18T05:52:05.255 | ENABLED: Price (systems)
2021-03-18T05:52:05.257 | ENABLED: Queue (systems)
2021-03-18T05:52:05.261 | ENABLED: Quotes (systems)
2021-03-18T05:52:05.263 | ENABLED: Raffles (systems)
2021-03-18T05:52:05.266 | ENABLED: Scrim (systems)
2021-03-18T05:52:05.268 | ENABLED: Timers (systems)
2021-03-18T05:52:05.272 | ENABLED: Top (systems)
2021-03-18T05:52:05.276 | ENABLED: UserInfo (systems)
2021-03-18T05:52:05.283 | EMOTES: Fetching global emotes
2021-03-18T05:52:05.302 | DISABLED: Duel (games)
2021-03-18T05:52:05.304 | DISABLED: FightMe (games)
2021-03-18T05:52:05.305 | DISABLED: Gamble (games)
2021-03-18T05:52:05.306 | DISABLED: Heist (games)
2021-03-18T05:52:05.308 | DISABLED: Roulette (games)
2021-03-18T05:52:05.309 | DISABLED: Seppuku (games)
2021-03-18T05:52:05.310 | DISABLED: Donationalerts (integrations)
2021-03-18T05:52:05.310 | DISABLED: OBSWebsocket (integrations)
2021-03-18T05:52:05.312 | DISABLED: PhillipsHue (integrations)
2021-03-18T05:52:05.312 | PHILLIPSHUE: Not connected to api
2021-03-18T05:52:05.313 | DISABLED: PUBG (integrations)
2021-03-18T05:52:05.314 | DISABLED: Qiwi (integrations)
2021-03-18T05:52:05.315 | DISABLED: StreamElements (integrations)
2021-03-18T05:52:05.316 | DISABLED: Streamlabs (integrations)
2021-03-18T05:52:05.316 | DISABLED: TipeeeStream (integrations)
2021-03-18T05:52:05.317 | DISABLED: Twitter (integrations)
2021-03-18T05:52:05.318 | TWITTER: Client disconnected from service
2021-03-18T05:52:07.554 | CURRENCY: fetched rates
2021-03-18T05:52:09.751 | EMOTES: Fetched global emotes
2021-03-18T05:52:15.195 |! Missing Broadcaster oAuth scope moderation:read to read channel moderators.
2021-03-18T05:52:27.399 |! Owners or broadcaster oauth is not set, all users are treated as CASTERS!!!
2021-03-18T05:54:42.884 | PUBSUB: Socket Opened
2021-03-18T05:54:42.886 | PUBSUB: Listening to channel-points-channel-v1.23393355
2021-03-18T05:54:42.887 | PUBSUB: Listening to chat_moderator_actions.23393355
2021-03-18T05:55:00.365 | Channel ID set to 23393355
2021-03-18T05:55:00.380 !!! ERROR !!! Broadcaster oauth is not properly set - hosts will not be loaded
2021-03-18T05:55:00.380 !!! ERROR !!! Broadcaster oauth is not properly set - subscribers will not be loaded
2021-03-18T05:55:00.382 | EMOTES: Fetching ffz emotes
2021-03-18T05:55:05.569 | TMI: bot joined channel deanosim
2021-03-18T05:55:08.714 | EMOTES: Fetched ffz emotes
2021-03-18T05:55:27.528 |! Broadcaster is not affiliate/partner, will not check subs
2021-03-18T05:56:00.391 |! Refreshing access token of broadcaster
2021-03-18T05:56:02.227 | Title/game changed outside of a bot => Destiny 2 | New Internet Who Dis? - Testing Settings and Breaking Shit
2021-03-18T05:56:05.290 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T05:56:05.291 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T05:56:10.437 | TMI: broadcaster joined channel deanosim
2021-03-18T05:57:34.098 | TMI: bot joined channel deanosim
2021-03-18T05:58:43.072 | TMI: bot parted channel deanosim
2021-03-18T05:58:51.724 | TMI: bot joined channel deanosim
2021-03-18T05:59:29.745 <<< test [deanosimbot]
2021-03-18T05:59:44.919 >>> test [pineapplebot_]
2021-03-18T06:00:52.907 | Bot is starting up (NodeJS: 14.16.0)
2021-03-18T06:00:56.062 | Initialized SQLite3 database (/app/shared/sogebot.db)
2021-03-18T06:00:56.856 | Bot timezone set to Australia/Sydney
2021-03-18T06:01:08.054 | No certificates were provided, serving only HTTP.
2021-03-18T06:01:08.543 | WebPanel is available at http://localhost:20000
2021-03-18T06:01:09.083 | ENABLED: Points (systems)
2021-03-18T06:01:24.057 |! Bot language is currently set to english
2021-03-18T06:01:43.545 | CURRENCY: fetching rates
2021-03-18T06:01:43.577 | ENABLED: Ranks (systems)
2021-03-18T06:01:43.582 | ENABLED: CustomCommands (systems)
2021-03-18T06:01:43.584 | ENABLED: Alias (systems)
2021-03-18T06:01:43.588 | DISABLED: Discord (integrations)
2021-03-18T06:01:43.590 | DISABLED: LastFM (integrations)
2021-03-18T06:01:43.591 | DISABLED: Spotify (integrations)
2021-03-18T06:01:43.591 | SPOTIFY: Client disconnected from service
2021-03-18T06:01:43.593 | ENABLED: Songs (systems)
2021-03-18T06:01:43.597 | ENABLED: Highlights (systems)
2021-03-18T06:01:43.608 | ENABLED: Bets (systems)
2021-03-18T06:01:43.612 | ENABLED: Checklist (systems)
2021-03-18T06:01:43.613 | ENABLED: Commercial (systems)
2021-03-18T06:01:43.614 | ENABLED: Cooldown (systems)
2021-03-18T06:01:43.617 | ENABLED: HowLongToBeat (systems)
2021-03-18T06:01:43.619 | ENABLED: Keywords (systems)
2021-03-18T06:01:43.621 | ENABLED: Levels (systems)
2021-03-18T06:01:43.626 | ENABLED: Moderation (systems)
2021-03-18T06:01:43.627 | ENABLED: Polls (systems)
2021-03-18T06:01:43.628 | ENABLED: Price (systems)
2021-03-18T06:01:43.631 | ENABLED: Queue (systems)
2021-03-18T06:01:43.633 | ENABLED: Quotes (systems)
2021-03-18T06:01:43.635 | ENABLED: Raffles (systems)
2021-03-18T06:01:43.638 | ENABLED: Scrim (systems)
2021-03-18T06:01:43.639 | ENABLED: Timers (systems)
2021-03-18T06:01:43.641 | ENABLED: Top (systems)
2021-03-18T06:01:43.644 | ENABLED: UserInfo (systems)
2021-03-18T06:01:43.650 | EMOTES: Fetching global emotes
2021-03-18T06:01:43.653 | DISABLED: Duel (games)
2021-03-18T06:01:43.655 | DISABLED: FightMe (games)
2021-03-18T06:01:43.656 | DISABLED: Gamble (games)
2021-03-18T06:01:43.659 | DISABLED: Heist (games)
2021-03-18T06:01:43.661 | DISABLED: Roulette (games)
2021-03-18T06:01:43.662 | DISABLED: Seppuku (games)
2021-03-18T06:01:43.662 | DISABLED: Donationalerts (integrations)
2021-03-18T06:01:43.663 | DISABLED: OBSWebsocket (integrations)
2021-03-18T06:01:43.664 | DISABLED: PhillipsHue (integrations)
2021-03-18T06:01:43.665 | PHILLIPSHUE: Not connected to api
2021-03-18T06:01:43.666 | DISABLED: PUBG (integrations)
2021-03-18T06:01:43.667 | DISABLED: Qiwi (integrations)
2021-03-18T06:01:43.668 | DISABLED: StreamElements (integrations)
2021-03-18T06:01:43.669 | DISABLED: Streamlabs (integrations)
2021-03-18T06:01:43.669 | DISABLED: TipeeeStream (integrations)
2021-03-18T06:01:43.670 | DISABLED: Twitter (integrations)
2021-03-18T06:01:43.671 | TWITTER: Client disconnected from service
2021-03-18T06:01:45.838 | CURRENCY: fetched rates
2021-03-18T06:01:51.777 | EMOTES: Fetched global emotes
2021-03-18T06:01:51.840 | Channel ID set to 23393355
2021-03-18T06:01:51.855 | EMOTES: Fetching ffz emotes
2021-03-18T06:01:55.821 | Channel ID set to 23393355
2021-03-18T06:01:55.822 | TMI: bot is reconnecting
2021-03-18T06:01:55.823 | TMI: broadcaster is reconnecting
2021-03-18T06:01:55.844 | Channel ID set to 23393355
2021-03-18T06:01:55.845 | TMI: bot is reconnecting
2021-03-18T06:01:55.847 | TMI: broadcaster is reconnecting
2021-03-18T06:02:00.333 | PUBSUB: Socket Opened
2021-03-18T06:02:00.338 | PUBSUB: Listening to channel-points-channel-v1.23393355
2021-03-18T06:02:00.339 | PUBSUB: Listening to chat_moderator_actions.23393355
2021-03-18T06:02:01.853 |! Refreshing access token of bot
2021-03-18T06:02:01.855 |! Refreshing access token of broadcaster
2021-03-18T06:02:05.823 |! Refreshing access token of bot
2021-03-18T06:02:05.826 |! Refreshing access token of broadcaster
2021-03-18T06:02:05.848 |! Refreshing access token of bot
2021-03-18T06:02:05.851 |! Refreshing access token of broadcaster
2021-03-18T06:02:07.997 | EMOTES: Fetched ffz emotes
2021-03-18T06:02:23.581 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:02:24.186 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:02:24.187 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:28.180 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:02:28.181 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:31.857 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:02:32.187 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:02:32.190 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:32.198 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:02:32.200 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:33.584 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:02:34.192 |! Refreshing access token of bot
2021-03-18T06:02:36.191 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:02:36.194 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:36.203 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:02:36.208 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:02:38.183 |! Refreshing access token of broadcaster
2021-03-18T06:02:42.196 |! Refreshing access token of bot
2021-03-18T06:02:42.207 |! Refreshing access token of broadcaster
2021-03-18T06:02:43.582 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:02:43.585 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:02:46.201 |! Refreshing access token of bot
2021-03-18T06:02:46.213 |! Refreshing access token of broadcaster
2021-03-18T06:02:53.583 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:00.210 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:03:00.212 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:01.534 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> Error: Channel required
      at Object.exports.channel (/app/node_modules/twitch-js/src/Chat/utils/validators.ts:58:11)
      at Chat.part (/app/node_modules/twitch-js/src/Chat/Chat.ts:384:26)
      at TMI.part (/app/src/bot/tmi.ts:334:25)
      at Socket.<anonymous> (/app/src/bot/panel.ts:341:11)
      at Socket.emit (events.js:315:20)
      at /app/node_modules/socket.io/dist/socket.js:435:32
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
} reason: Error: Channel required
2021-03-18T06:03:03.589 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:08.218 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:03:08.219 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:08.220 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:03:08.221 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:10.217 |! Refreshing access token of bot
2021-03-18T06:03:11.893 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:11.996 | TMI: bot is not properly set, cannot join empty channel
2021-03-18T06:03:12.223 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:03:12.227 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:13.589 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:13.590 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:18.220 |! Refreshing access token of bot
2021-03-18T06:03:18.225 |! Refreshing access token of broadcaster
2021-03-18T06:03:19.905 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:20.233 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:03:20.236 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:20.243 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:03:20.245 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:22.233 |! Refreshing access token of broadcaster
2021-03-18T06:03:23.589 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:23.598 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:30.241 |! Refreshing access token of bot
2021-03-18T06:03:30.249 |! Refreshing access token of broadcaster
2021-03-18T06:03:31.903 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - Error: timeout of 20000ms exceeded
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:280:16)
    at Object.onceWrapper (events.js:421:28)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/app/node_modules/follow-redirects/index.js:166:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-03-18T06:03:31.905 |! Broadcaster is not affiliate/partner, will not check subs
2021-03-18T06:03:33.588 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:33.593 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:33.596 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:35.932 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:35.968 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:39.914 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - Error: timeout of 20000ms exceeded
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:280:16)
    at Object.onceWrapper (events.js:421:28)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/app/node_modules/follow-redirects/index.js:166:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-03-18T06:03:43.592 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:43.596 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:43.610 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:48.265 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:03:48.267 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:03:53.589 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:53.591 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:53.595 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:03:53.599 !!! ERROR !!! https://api.twitch.tv/helix/channels?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:55.937 !!! ERROR !!! https://api.twitch.tv/helix/channels?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:55.972 !!! ERROR !!! https://api.twitch.tv/helix/channels?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:03:58.272 |! Refreshing access token of bot
2021-03-18T06:03:59.923 !!! ERROR !!! https://api.twitch.tv/helix/channels?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:04:03.606 !!! ERROR !!! https://api.twitch.tv/helix/streams?user_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:04:03.615 !!! ERROR !!! https://api.twitch.tv/helix/streams/tags?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:04:03.652 !!! ERROR !!! https://api.twitch.tv/helix/users/follows?to_id=23393355&first=100 - timeout of 20000ms exceeded
2021-03-18T06:04:03.658 !!! ERROR !!! https://api.twitch.tv/helix/channels?broadcaster_id=23393355 - timeout of 20000ms exceeded
2021-03-18T06:04:04.279 !!! ERROR !!! Access token of bot was not refreshed.
2021-03-18T06:04:04.280 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18T06:04:04.307 !!! ERROR !!! Access token of broadcaster was not refreshed.
2021-03-18T06:04:04.308 !!! ERROR !!! Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

no exception.log files

**Comment by sogehige** [comment]
Hi, thanks for issue.

Are you sure you have correctly set tokens for broadcaster and bot? Also this seems like some network or twitch issues as 20s to reach twitch api endpoint is not normal

**Comment by Deanosim** [comment]
Yeah I can't actually access twitchtokengenerator.com anymore either it's giving me the 403 Forbidden error when trying to get tokens. I get the feeling twitch is blocking me from accessing the helix api. If I connect to a vpn and go to twitchtokengenerator.com it works fine... and what's even more weird is I've got Phantombot running and it hasn't had any problems connecting. So I'm not sure what's going on.

**Comment by Deanosim** [comment]
What's even more weird is I connected the bot to a vpn with a dedicated vpn to see if that worked, and it did until I restarted it and then now it's giving the same 403 forbidden error, I think twitch is actually just blacklisting my IP addresses every time I connect the bot.

**Comment by Deanosim** [comment]
after a lot of testing I force set the dns on the docker container using --dns=1.1.1.1 and --dns=8.8.8.8 and now it seems to work. I still can't access twitchtokengenerator.com for whatever reason so that's a little bit annoying. But I shall keep an eye on sogebot and make sure it stays connected and do a few restarts to see if it can connect. It's a very weird problem.

**Comment by sogehige** [comment]
I know that yesterday was some kind of issues with google DNS, so that might have cause your issue. For refreshing of tokens we are using twitchtokengenerator so if it fails for you then there is (currently) no way to use other service or to use own clientid for a bot.

**Comment by Deanosim** [comment]
Well I've kept an eye on it for the past few days, and it seems to be working now. I'm in contact with twitchtokengenerator.com too to get my IP unblacklisted. Thanks for your help, 99% sure it was a DNS problem like you mentioned.
