### ISSUE TITLE
!songrequest won't work with 5.11.2 release

### ISSUE THREAD

**Issue by xotlr43** [sogehige/sogeBot#674]
### Expected behavior
!songrequest won't work anymore. 

### Actual behavior

!songrequest video-url
 !!! ERROR !!! Error: This video is unavailable
    at request (D:\Streaming\sogeBot-5.11.2\node_modules\ytdl-core\lib\info.js:220:16)
    at IncomingMessage.res.on (D:\Streaming\sogeBot-5.11.2\node_modules\miniget\lib\index.js:75:11)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) [function: Songs.prototype.addSongToQueue#1]

### Additional informations

GENERAL
OS: npm/5.5.1 node/v9.3.0 win32 x64
DB: nedb
Bot version: 5.11.2
Bot uptime: 1551.704
Bot lang: en
Bot mute: false
Moderator glossybeanbot:
SYSTEMS | timers, customcommands, keywords, songs, alias, moderation, cooldown, highlights
Moderator glossybeanbot: WIDGETS | chat, twitch
Moderator glossybeanbot: API | HELIX 128/0 | KRAKEN 192/0 | TMI 96/0
Moderator glossybeanbot: WEBHOOKS |
Moderator glossybeanbot: OAUTH | BOT false | BROADCASTER false

**Comment by sogehige** [comment]
This error was due to some API changes in YT for embed videos, latest ytdl-core should fix that issue
