### ISSUE TITLE
Problem starting Bot | CentOS 7. 

### ISSUE THREAD

**Issue by brocc0li** [sogehige/sogeBot#704]
### Expected behavior
Problem starting Bot | CentOS 7. 

Error on startup: 
` > sogebot@5.12.0-SNAPSHOT start /root/botss/TwitchBotMaster
> node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true

/root/botss/TwitchBotMaster/tools/migrate.js:8
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
`

Installed: NPM / NODE on server. 
Java is installed.
Config is renamed and configured (NEDB)
install.sh have been run.
Fresh install of CentOs

### Actual behavior
Dosnt start up like it should.
### Steps to reproduce
Start bot.
### Additional informations
I think i have installed everything that is needed to make this bot run. If not What do i miss?
Installed: Java, NPM, Node.

**Comment by sogehige** [comment]
You need Node 8 or 9 to run a bot

**Comment by brocc0li** [comment]
Got another error on NodeJS 8.9.4 (NPM Version 5.6.0

https://image.prntscr.com/image/Lcnfua-0S32IJem_XBccog.png

**Comment by sogehige** [comment]
please try in bot folder
`rm -rf node_modules; npm install`

**Comment by alreadylostmyself** [comment]
Did you tryed rm -rf node_modules; npm install?

**Comment by brocc0li** [comment]
had it running for one day.. Now i get this error when i try to start the bot: https://image.prntscr.com/image/Uz4K-fVMQk_LTT3sQUZssA.png

**Comment by sogehige** [comment]
You should not run latest master, if you are expecting bug free bot (even released one may have bugs, but master surely have). Also, this is different bug in migration tool, better approach would be to create separate issue.

Also, if you had bot running, then I don't see why it shouldn't have db version set to 5.12. Did you remove something in db/nedb folder?

Bug with migration should be resolved.

**Comment by sogehige** [comment]
Also, you can get help at https://discordapp.com/invite/52KpmuH
