### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#935]
### Actual behavior
2018-04-19T21:37:01.361Z <<< qwe [user]
2018-04-19T21:37:01.553Z !!! ERROR !!! MongoError: Cannot apply $inc to a value of non-numeric type. {_id: ObjectId('5ad6ff54f698fd5f883c6325')} has the field 'messages' of non-numeric type String
at Function.MongoError.create (/home/node_modules/mongodb-core/lib/error.js:45:10)
 at toError (/home/node_modules/mongodb/lib/utils.js:149:22)
at /home/node_modules/mongodb/lib/collection.js:1035:39
at /home/node_modules/mongodb-core/lib/connection/pool.js:544:18
at process._tickCallback (internal/process/next_tick.js:176:11)

**Comment by sogehelper** [comment]
Seems like it sometimes when someone type in chat, but maybe by other thing.. when it "appears" nothing happend. No duels, no games, nothing. Just messages in logs

**Comment by sogehige** [comment]
what that user looks like in your `users` collection?

**Comment by sogehelper** [comment]
how i can find him?

**Comment by sogehige** [comment]
2018-04-19T21:37:01.361Z <<< qwe [`user`]

you should search for `user` in `users` colelction

**Comment by sogehige** [comment]
Fixed for `7.4.0`
