### ISSUE TITLE
 UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#940]
node ./tools/migrate
(node:14592) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key                                         error collection: icebot_db.users index: username_1 dup key: { : "boonee007" }
    at /home/bots/icebot/node_modules/mongodb-core/lib/connection/pool.js:598:61
    at authenticateStragglers (/home/bots/icebot/node_modules/mongodb-core/lib/c                                        onnection/pool.js:516:16)
    at Connection.messageHandler (/home/bots/icebot/node_modules/mongodb-core/li                                        b/connection/pool.js:552:5)
    at emitMessageHandler (/home/bots/icebot/node_modules/mongodb-core/lib/conne                                        ction/connection.js:309:10)
    at Socket.<anonymous> (/home/bots/icebot/node_modules/mongodb-core/lib/conne                                        ction/connection.js:452:17)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
(node:14592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                         error originated either by throwing inside of an async function without a catch                                         block, or by rejecting a promise which was not handled with .catch(). (rejectio                                        n id: 1)
(node:14592) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr                                        ecated. In the future, promise rejections that are not handled will terminate th                                        e Node.js process with a non-zero exit code.

Getting the following error on migration script on bot start. Unable to start bot. 

Bot Version 7.3.0

**Comment by sogehige** [comment]
Please use cleanup tool in 7.3.1
