### ISSUE TITLE
Error in Console (NEDB)

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#941]
One of my bots is getting the following error.

"0|GIGSBOT  | 2018-04-23T17:33:42.439Z !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
0|GIGSBOT  |   <rejected> Error: Don't use the $inc modifier on non-number fields
0|GIGSBOT  |     at Object.lastStepModifierFunctions.$inc (/home/bots/gigsbot/node_modules/nedb/lib/model.js:382:13)
0|GIGSBOT  |     at Object.$inc (/home/bots/gigsbot/node_modules/nedb/lib/model.js:417:42)
0|GIGSBOT  |     at Object.$inc (/home/bots/gigsbot/node_modules/nedb/lib/model.js:423:34)
0|GIGSBOT  |     at /home/bots/gigsbot/node_modules/nedb/lib/model.js:471:29
0|GIGSBOT  |     at Array.forEach (<anonymous>)
0|GIGSBOT  |     at /home/bots/gigsbot/node_modules/nedb/lib/model.js:470:12
0|GIGSBOT  |     at Array.forEach (<anonymous>)
0|GIGSBOT  |     at Object.modify (/home/bots/gigsbot/node_modules/nedb/lib/model.js:458:15)
0|GIGSBOT  |     at /home/bots/gigsbot/node_modules/nedb/lib/datastore.js:618:33
0|GIGSBOT  |     at /home/bots/gigsbot/node_modules/nedb/lib/datastore.js:329:14 } reason: Error: Don't use the $inc modifier on non-number fields
"

Unsure of the cause.

**Comment by ic3dr460n** [comment]
All users affected. Whenever someone says something in chat it triggers that error.

[users.zip](https://github.com/sogehige/sogeBot/files/1940383/users.zip)
